#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent

REQUIRED_PATHS: dict[str, list[str]] = {
    "root_docs": [
        "AGENTS.md",
        "README.md",
        "Documentation.md",
        "progress.md",
        "tasks.md",
        "samples_progress.md",
    ],
    "specs": [
        "specs/00-document-map.md",
        "specs/01-charter-and-decision-levels.md",
        "specs/02-system-overview.md",
        "specs/03-layer-model.md",
        "specs/04-mir-core.md",
        "specs/05-mirrorea-fabric.md",
        "specs/06-prismcascade-positioning.md",
        "specs/07-typed-effects-wiring-platform.md",
        "specs/08-cross-system-relations.md",
        "specs/09-invariants-and-constraints.md",
        "specs/10-open-questions.md",
        "specs/11-roadmap-and-workstreams.md",
        "specs/12-decision-register.md",
        "specs/13-type-system-lifetime-fallback.md",
        "specs/14-contract-subtyping-layer-compatibility.md",
        "specs/15-cut-save-load-checkpoint.md",
        "specs/16-runtime-package-adapter-hotplug.md",
        "specs/17-mirrorea-spaces-alpha-scope.md",
        "specs/18-practical-alpha1-scope.md",
        "specs/19-verification-stratification.md",
        "specs/20-cut-save-load-semantics.md",
        "specs/21-auth-layer-algebra.md",
        "specs/22-observability-devtools-semantics.md",
        "specs/23-typed-external-host-boundary.md",
        "specs/24-operational-alpha05-alpha08-readiness.md",
        "specs/25-product-alpha1-public-boundary.md",
        "specs/26-operational-product-sample-suite.md",
        "specs/27-spatial-portal-and-shard-extension-boundary.md",
        "specs/28-mir-computational-core.md",
        "specs/29-transform-posegraph-semantics.md",
        "specs/30-projection-and-backend-boundary.md",
        "specs/31-engine-wasm-ffi-adapter-boundary.md",
        "specs/32-autonomous-execution-and-completion-contract.md",
        "specs/33-full-system-v1-scope.md",
        "specs/34-textual-mir-alpha-grammar.md",
        "specs/35-mir-typed-ir-and-interpreter.md",
        "specs/36-projection-ir-and-boundary-preservation.md",
        "specs/37-posegraph-runtime-semantics.md",
        "specs/38-engine-provider-admission.md",
    ],
    "policies": [
        ".docs/progress-task-axes.md",
        ".docs/continuous-task-policy.md",
        ".docs/current-l2-source-sample-authoring-policy.md",
    ],
    "plan": [
        "plan/00-index.md",
        "plan/01-status-at-a-glance.md",
        "plan/11-roadmap-near-term.md",
        "plan/17-research-phases-and-autonomy-gates.md",
        "plan/19-repository-map-and-taxonomy.md",
        "plan/39-type-system-freeze-roadmap.md",
        "plan/40-layer-compatibility-freeze-roadmap.md",
        "plan/41-save-load-checkpoint-roadmap.md",
        "plan/42-runtime-package-avatar-roadmap.md",
        "plan/43-alpha-e2e-roadmap.md",
        "plan/44-practical-alpha1-roadmap.md",
        "plan/45-operational-alpha05-roadmap.md",
        "plan/46-operational-alpha08-roadmap.md",
        "plan/47-operational-alpha09-devtools-roadmap.md",
        "plan/48-theory-freeze-proof-obligations.md",
        "plan/49-host-io-and-session-runtime-roadmap.md",
        "plan/50-product-alpha1-public-boundary-roadmap.md",
        "plan/51-operational-product-sample-roadmap.md",
        "plan/52-portal-spatial-world-roadmap.md",
        "plan/53-mir-computational-core-roadmap.md",
        "plan/54-transform-posegraph-roadmap.md",
        "plan/55-projection-backend-roadmap.md",
        "plan/56-engine-adapter-roadmap.md",
        "plan/57-autonomous-computational-core-master-plan.md",
        "plan/58-full-system-v1-roadmap.md",
        "plan/59-textual-mir-roadmap.md",
        "plan/60-computational-runtime-roadmap.md",
        "plan/61-posegraph-runtime-roadmap.md",
        "plan/62-projection-backend-roadmap.md",
        "plan/63-engine-provider-roadmap.md",
    ],
    "scripts": [
        "scripts",
        "scripts/README.md",
        "scripts/textual_mir_samples.py",
        "scripts/mir_computational_samples.py",
        "scripts/posegraph_samples.py",
        "scripts/projection_boundary_samples.py",
        "scripts/engine_adapter_boundary_samples.py",
        "scripts/product_alpha1_release_check.py",
        "scripts/operational_product_samples.py",
        "scripts/tests/test_mir_computational_samples.py",
        "scripts/tests/test_posegraph_samples.py",
        "scripts/tests/test_projection_boundary_samples.py",
        "scripts/tests/test_engine_adapter_boundary_samples.py",
        "scripts/tests/test_product_alpha1_release_check.py",
        "scripts/tests/test_operational_product_samples.py",
        "scripts/tests/test_textual_mir_samples.py",
    ],
    "samples": [
        "samples/README.md",
        "samples/full-system-v1/README.md",
        "samples/full-system-v1/computational/README.md",
        "samples/full-system-v1/computational/matrix.json",
        "samples/full-system-v1/computational/add-one-positive/README.md",
        "samples/full-system-v1/computational/add-one-positive/src/add-one.mir",
        "samples/full-system-v1/computational/add-one-positive/expected/parse.json",
        "samples/full-system-v1/computational/host-boundary-positive/README.md",
        "samples/full-system-v1/computational/host-boundary-positive/src/host-boundary-add-one.mir",
        "samples/full-system-v1/computational/host-boundary-positive/expected/parse.json",
        "samples/full-system-v1/computational/malformed-function-negative/README.md",
        "samples/full-system-v1/computational/malformed-function-negative/src/malformed-function.mir",
        "samples/full-system-v1/computational/malformed-function-negative/expected/parse.json",
        "samples/full-system-v1/computational/malformed-perform-negative/README.md",
        "samples/full-system-v1/computational/malformed-perform-negative/src/malformed-perform.mir",
        "samples/full-system-v1/computational/malformed-perform-negative/expected/parse.json",
        "samples/full-system-v1/computational/unresolved-import-negative/README.md",
        "samples/full-system-v1/computational/unresolved-import-negative/src/unresolved-import.mir",
        "samples/full-system-v1/computational/unresolved-import-negative/expected/parse.json",
        "samples/full-system-v1/computational/missing-type-annotation-negative/README.md",
        "samples/full-system-v1/computational/missing-type-annotation-negative/src/missing-type-annotation.mir",
        "samples/full-system-v1/computational/missing-type-annotation-negative/expected/parse.json",
        "samples/full-system-v1/computational/malformed-record-negative/README.md",
        "samples/full-system-v1/computational/malformed-record-negative/src/malformed-record.mir",
        "samples/full-system-v1/computational/malformed-record-negative/expected/parse.json",
        "samples/full-system-v1/computational/malformed-transition-negative/README.md",
        "samples/full-system-v1/computational/malformed-transition-negative/src/malformed-transition.mir",
        "samples/full-system-v1/computational/malformed-transition-negative/expected/parse.json",
        "samples/full-system-v1/computational/malformed-capability-negative/README.md",
        "samples/full-system-v1/computational/malformed-capability-negative/src/malformed-capability.mir",
        "samples/full-system-v1/computational/malformed-capability-negative/expected/parse.json",
        "samples/full-system-v1/computational/contract-clause-position-negative/README.md",
        "samples/full-system-v1/computational/contract-clause-position-negative/src/contract-clause-position.mir",
        "samples/full-system-v1/computational/contract-clause-position-negative/expected/parse.json",
        "samples/alpha/README.md",
        "samples/product-alpha1/README.md",
        "samples/product-alpha1/demo/README.md",
        "samples/product-alpha1/demo/package.mir.json",
        "samples/product-alpha1/operational/README.md",
        "samples/product-alpha1/operational/templates/README.md",
        "samples/product-alpha1/operational/templates/world-core-starter/README.md",
        "samples/product-alpha1/operational/templates/world-core-starter/package.mir.json",
        "samples/product-alpha1/operational/templates/membership-chat-starter/README.md",
        "samples/product-alpha1/operational/templates/membership-chat-starter/package.mir.json",
        "samples/product-alpha1/operational/templates/sugoroku-world-starter/README.md",
        "samples/product-alpha1/operational/templates/sugoroku-world-starter/package.mir.json",
        "samples/product-alpha1/operational/world-core/README.md",
        "samples/product-alpha1/operational/world-core/package.mir.json",
        "samples/product-alpha1/operational/membership-chat/README.md",
        "samples/product-alpha1/operational/membership-chat/package.mir.json",
        "samples/product-alpha1/operational/sugoroku-world/README.md",
        "samples/product-alpha1/operational/sugoroku-world/package.mir.json",
        "samples/product-alpha1/operational/portal-worldlink/README.md",
        "samples/product-alpha1/operational/portal-worldlink/package.mir.json",
        "samples/product-alpha1/operational/two-shard-hard-boundary/README.md",
        "samples/product-alpha1/operational/two-shard-hard-boundary/package.mir.json",
        "samples/product-alpha1/operational/packages/debug-layer/package.mir.json",
        "samples/product-alpha1/operational/packages/auth-layer/package.mir.json",
        "samples/product-alpha1/operational/packages/rate-limit-layer/package.mir.json",
        "samples/product-alpha1/operational/packages/placeholder-object/package.mir.json",
        "samples/product-alpha1/operational/packages/custom-avatar-preview/package.mir.json",
        "samples/product-alpha1/operational/deployments/local/deployment.profile.json",
        "samples/product-alpha1/operational/deployments/docker/docker-compose.operational.yml",
        "samples/product-alpha1/operational/deployments/projection/projection.profile.json",
        "samples/product-alpha1/operational/future/portal-worldlink/README.md",
        "samples/product-alpha1/operational/future/portal-worldlink/portal-worldlink.package.mir.json",
        "samples/product-alpha1/operational/future/gradient-observation.profile.json",
        "samples/product-alpha1/operational/future/two-shard-hard-boundary/README.md",
        "samples/product-alpha1/operational/future/spatial-shard-future.profile.json",
        "samples/product-alpha1/demo/packages/debug-layer/package.mir.json",
        "samples/product-alpha1/demo/packages/auth-layer/package.mir.json",
        "samples/product-alpha1/demo/packages/rate-limit-layer/package.mir.json",
        "samples/product-alpha1/demo/packages/placeholder-object/package.mir.json",
        "samples/product-alpha1/demo/packages/custom-avatar-preview/package.mir.json",
        "samples/product-alpha1/docker/README.md",
        "samples/product-alpha1/docker/docker-compose.product-alpha1.yml",
        "samples/product-alpha1/computational/README.md",
        "samples/product-alpha1/computational/matrix.json",
        "samples/product-alpha1/computational/add-one-pure-mir/README.md",
        "samples/product-alpha1/computational/add-one-pure-mir/add-one-pure-mir.mir",
        "samples/product-alpha1/computational/variables-scope/README.md",
        "samples/product-alpha1/computational/variables-scope/variables-scope.mir",
        "samples/product-alpha1/computational/arrays-bounds/README.md",
        "samples/product-alpha1/computational/arrays-bounds/arrays-bounds.mir",
        "samples/product-alpha1/computational/records-vec3/README.md",
        "samples/product-alpha1/computational/records-vec3/records-vec3.mir",
        "samples/product-alpha1/computational/control-flow/README.md",
        "samples/product-alpha1/computational/control-flow/control-flow.mir",
        "samples/product-alpha1/computational/imports-functions/README.md",
        "samples/product-alpha1/computational/imports-functions/imports-functions.mir",
        "samples/product-alpha1/computational/host-io-internal-transform/README.md",
        "samples/product-alpha1/computational/host-io-internal-transform/host-io-internal-transform.mir",
        "samples/product-alpha1/posegraph/README.md",
        "samples/product-alpha1/posegraph/matrix.json",
        "samples/product-alpha1/posegraph/avatar-head-transform/README.md",
        "samples/product-alpha1/posegraph/avatar-head-transform/avatar-head-transform.mir",
        "samples/product-alpha1/posegraph/anchored-object/README.md",
        "samples/product-alpha1/posegraph/anchored-object/anchored-object.mir",
        "samples/product-alpha1/posegraph/sparkle-fallback-anchor/README.md",
        "samples/product-alpha1/posegraph/sparkle-fallback-anchor/sparkle-fallback-anchor.mir",
        "samples/product-alpha1/posegraph/no-split-frame-positive/README.md",
        "samples/product-alpha1/posegraph/no-split-frame-positive/no-split-frame-positive.mir",
        "samples/product-alpha1/posegraph/split-frame-negative/README.md",
        "samples/product-alpha1/posegraph/split-frame-negative/split-frame-negative.mir",
        "samples/product-alpha1/posegraph/save-load-roundtrip/README.md",
        "samples/product-alpha1/posegraph/save-load-roundtrip/save-load-roundtrip.mir",
        "samples/product-alpha1/posegraph/stale-anchor-after-membership-advance/README.md",
        "samples/product-alpha1/posegraph/stale-anchor-after-membership-advance/stale-anchor-after-membership-advance.mir",
        "samples/product-alpha1/posegraph/anchor-switch-frontier-negative/README.md",
        "samples/product-alpha1/posegraph/anchor-switch-frontier-negative/anchor-switch-frontier-negative.mir",
        "samples/product-alpha1/posegraph/stale-anchor-reacquire-required/README.md",
        "samples/product-alpha1/posegraph/stale-anchor-reacquire-required/stale-anchor-reacquire-required.mir",
        "samples/product-alpha1/projection/README.md",
        "samples/product-alpha1/projection/matrix.json",
        "samples/product-alpha1/projection/server-client-target-manifest/server-client-target-manifest.json",
        "samples/product-alpha1/projection/packet-boundary-schema/packet-boundary-schema.json",
        "samples/product-alpha1/projection/ffi-boundary-schema/ffi-boundary-schema.json",
        "samples/product-alpha1/projection/manifest-provider-compatibility/manifest-provider-compatibility.json",
        "samples/product-alpha1/engine-adapter/README.md",
        "samples/product-alpha1/engine-adapter/matrix.json",
        "samples/product-alpha1/engine-adapter/renderer/renderer.contract.json",
        "samples/product-alpha1/engine-adapter/input-device/input-device.contract.json",
        "samples/product-alpha1/engine-adapter/asset-loader/asset-loader.contract.json",
        "samples/product-alpha1/engine-adapter/physics-spatial-query/physics-spatial-query.contract.json",
        "samples/product-alpha1/engine-adapter/host-runtime-bridge/host-runtime-bridge.contract.json",
        "samples/product-alpha1/engine-adapter/wasm-sandbox/wasm-sandbox.contract.json",
        "samples/product-alpha1/engine-adapter/native-library-bridge/native-library-bridge.contract.json",
        "samples/product-alpha1/engine-adapter/viewer-diagnostic-exporter/viewer-diagnostic-exporter.contract.json",
        "samples/practical-alpha1/README.md",
        "samples/practical-alpha1/packages/README.md",
        "samples/practical-alpha1/source/README.md",
        "samples/practical-alpha1/expected/README.md",
        "samples/practical-alpha1/docker/README.md",
        "samples/alpha/lifetime-fallback/README.md",
        "samples/alpha/contract-variance/README.md",
        "samples/alpha/cut-save-load/README.md",
        "samples/alpha/local-runtime/README.md",
        "samples/alpha/layer-insertion/README.md",
        "samples/alpha/network-docker/README.md",
        "samples/alpha/hotplug-runtime/README.md",
        "samples/alpha/avatar-runtime/README.md",
        "samples/alpha/visualization/README.md",
        "samples/alpha/e2e/README.md",
        "samples/not_implemented/README.md",
    ],
    "supporting_dirs": [
        "docs/reports",
        "docs/hands_on/README.md",
        "docs/hands_on/product_alpha1_01.md",
        "docs/hands_on/operational_product_sample_01.md",
        "docs/hands_on/operational_package_authoring_01.md",
        "docs/hands_on/operational_backend_inventory_01.md",
        "docs/hands_on/operational_gradient_observation_profile_01.md",
        "docs/hands_on/operational_portal_shard_starter_boundary_01.md",
        "docs/hands_on/mir_computational_core_01.md",
        "docs/hands_on/transform_posegraph_01.md",
        "docs/hands_on/autonomous_execution_01.md",
        "docs/hands_on/full_system_v1_roadmap_01.md",
        "docs/research_abstract/README.md",
        "docs/research_abstract",
        "docs/research_abstract/product_alpha1_01.md",
        "docs/research_abstract/operational_product_sample_01.md",
        "docs/research_abstract/operational_package_authoring_01.md",
        "docs/research_abstract/operational_backend_inventory_01.md",
        "docs/research_abstract/operational_gradient_observation_profile_01.md",
        "docs/research_abstract/operational_portal_shard_starter_boundary_01.md",
        "docs/research_abstract/mir_computational_core_01.md",
        "docs/research_abstract/autonomous_execution_01.md",
        "docs/research_abstract/full_system_v1_roadmap_01.md",
        "samples/alpha",
        "samples/product-alpha1",
        "samples/product-alpha1/computational",
        "samples/product-alpha1/posegraph",
        "samples/product-alpha1/projection",
        "samples/product-alpha1/engine-adapter",
        "samples/product-alpha1/demo",
        "samples/product-alpha1/operational",
        "samples/product-alpha1/docker",
        "samples/full-system-v1",
        "samples/full-system-v1/computational",
        "samples/practical-alpha1",
        "samples/practical-alpha1/packages",
        "samples/practical-alpha1/source",
        "samples/practical-alpha1/expected",
        "samples/practical-alpha1/docker",
        "samples/clean-near-end",
        "samples/clean-near-end/sugoroku-world",
        "crates/mir-runtime",
        "sub-agent-pro",
        "sub-agent-pro/alpha-0",
        "sub-agent-pro/alpha-1",
        "sub-agent-pro/product-alpha1-001",
        "sub-agent-pro/operational-product-sample-001",
        "sub-agent-pro/full-system-completion-001",
        "sub-agent-pro/mirrorea_mir_computational_core_handoff.md",
    ],
}


def build_status() -> dict[str, object]:
    present: list[str] = []
    missing: list[str] = []
    for paths in REQUIRED_PATHS.values():
        for rel_path in paths:
            if (REPO_ROOT / rel_path).exists():
                present.append(rel_path)
            else:
                missing.append(rel_path)
    return {
        "repo_root": str(REPO_ROOT),
        "required_count": len(present) + len(missing),
        "present_count": len(present),
        "missing_count": len(missing),
        "present": present,
        "missing": missing,
        "status": "ok" if not missing else "missing",
    }


def format_pretty(status: dict[str, object]) -> str:
    lines = [
        "source hierarchy check",
        f"  repo_root: {status['repo_root']}",
        f"  required: {status['required_count']}",
        f"  present: {status['present_count']}",
        f"  missing: {status['missing_count']}",
    ]
    missing = status["missing"]
    if missing:
        lines.append("  missing paths:")
        for rel_path in missing:
            lines.append(f"    - {rel_path}")
    else:
        lines.append("  all required paths present")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--format", choices=["pretty", "json"], default="pretty")
    args = parser.parse_args()

    status = build_status()
    if args.format == "json":
        print(json.dumps(status, indent=2, ensure_ascii=False))
    else:
        print(format_pretty(status))
    return 0 if status["missing_count"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
