import MirroreaProofFirstOwnerCommitJournal
import MirroreaProofFirstOwnerInstallationHistory
import MirroreaProofFirstPaidHeadPhase
import SourcePublicationWorkerSupport
namespace MirroreaProofFirst.CohortCommitJournal

-- Selected cohort's local fields. Lists represent sets (order is not observable)
-- except pending, whose exact request/source ordinal is an occurrence. Source
-- snapshots and produced envelopes are complete typed values, not digests.
structure Memory (p a : Nat) where
  bootstrapped : Bool
  snapshot : Option (SourcePublicationWorker.PrivateOutput p a)
  initialized : List (Fin p)
  freezes : List (Fin p × Nat)
  installs : List (Fin p × Nat)
  produced : List OwnerReceipt.Envelope
  pendingPayment : Option (PaidHeadPhase.Pending p)

def insert [DecidableEq α] (value : α) (values : List α) : List α :=
  if value ∈ values then values else value::values

inductive Store (p a : Nat) where
  | bootstrap
  | snapshot (value : Option (SourcePublicationWorker.PrivateOutput p a))
  | initialized (owner : Fin p)
  | frozen (owner : Fin p) (revision : Nat)
  | installed (owner : Fin p) (revision : Nat)
  | payment (value : PaidHeadPhase.Pending p)
  | clearPayment
  | produced (value : OwnerReceipt.Envelope)

def write (memory : Memory p a) : Store p a → Memory p a
  | .bootstrap => {memory with bootstrapped:=true}
  | .snapshot value => {memory with snapshot:=value}
  | .initialized owner => {memory with initialized:=insert owner memory.initialized}
  | .frozen owner revision => {memory with freezes:=insert (owner,revision) memory.freezes}
  | .installed owner revision => {memory with installs:=insert (owner,revision) memory.installs}
  | .payment value => {memory with pendingPayment:=some value}
  | .clearPayment => {memory with pendingPayment:=none}
  | .produced value => {memory with produced:=insert value memory.produced}

-- Receipts here describe completed inner boundaries. Their provenance is an
-- EXTERNAL composition obligation, not authority generated by these types:
-- owner uses actual writer return, source uses actual parsed native source reply,
-- work uses actual matching finish reply, and bootstrap is only a write return.
-- In particular source snapshot stores additionally require prior lease notification/cancellation;
-- that writer/cohort cross-field barrier is NOT enforced by this local model,
-- and paid metadata must come from the same source-head query occurrence.
inductive Receipt (p a : Nat) where
  | bootstrapReturned
  | sourceReply (value : Option (SourcePublicationWorker.PrivateOutput p a)) (clear : Bool)
  | ownerReturned (owner : Fin p) (command : OwnerEndpoint.Command p a)
      (reply : Sum Nat OwnerReceipt.Envelope) (payment : Option (PaidHeadPhase.Pending p))
  | workFinished (value : OwnerReceipt.Envelope)

def ownerStores (before : Memory p a) (owner : Fin p) (command : OwnerEndpoint.Command p a)
    (reply : Sum Nat OwnerReceipt.Envelope) (payment : Option (PaidHeadPhase.Pending p)) : List (Store p a) :=
  (match command,reply with
    | .owner (.initialize _),.inl 10 => if owner ∈ before.initialized then [] else [.initialized owner]
    | _,_ => []) ++
  (payment.toList.map Store.payment) ++
  (match command,reply with
    | .owner (.initialize _),.inl 10 => [.installed owner 0]
    | .freeze revision,.inl 12 => [.frozen owner revision]
    | .owner (.install revision _),.inl 7 => [.installed owner revision]
    | _,_ => [])

def recipe (before : Memory p a) : Receipt p a → List (Store p a)
  | .bootstrapReturned => [.bootstrap]
  | .sourceReply value clear => [.snapshot value] ++ if clear then [.clearPayment] else []
  | .ownerReturned owner command reply payment => ownerStores before owner command reply payment
  | .workFinished value => [.produced value]

-- No recipe constructor proves its own authenticity. This nontrivial binding
-- lemma derives initialization's installed revision from the REAL native step;
-- an arbitrary current publication label cannot replace zero.
theorem initialized_revision_zero
    (ran : OwnerEndpointBudget.transition assigned scope capacity before
      (.owner (.initialize image)) = (next,.inl 10)) :
    ∃ owner, next.owner = some owner ∧ owner.owner.core.revision = 0 := by
  exact OwnerInstallationHistory.successful_observation ran (current:=(0,image)) rfl

structure State (p a : Nat) where
  memory : Memory p a
  pending : List (Store p a)
  call : Option Nat
  gate : Bool
  retired : Bool

inductive Action (p a : Nat) where
  | enter (call : Nat)
  | arm (receipt : Receipt p a)
  | commit
  | returnCall
  | retire
  | releaseRetired

-- Distinguish ordinary release from failed cleanup: the former requires an
-- empty local debt, the latter preserves every store still owed. A retained
-- protocol payment is a memory field and does not prevent ordinary release.
inductive Step : State p a → Action p a → State p a → Prop where
  | enter : Step ⟨memory,[],none,false,false⟩ (.enter callId) ⟨memory,[],some callId,true,false⟩
  | arm : Step ⟨memory,[],some callId,true,false⟩ (.arm receipt)
      ⟨memory,recipe memory receipt,some callId,true,false⟩
  | commit : Step ⟨memory,store::rest,some callId,true,false⟩ .commit
      ⟨write memory store,rest,some callId,true,false⟩
  | returnCall : Step ⟨memory,[],some callId,true,false⟩ .returnCall ⟨memory,[],none,false,false⟩
  | retire : Step ⟨memory,pending,call,gate,false⟩ .retire ⟨memory,pending,call,gate,true⟩
  | releaseRetired : Step ⟨memory,pending,some callId,true,true⟩ .releaseRetired
      ⟨memory,pending,none,false,true⟩

def advance : State p a → Action p a → Option (State p a)
  | ⟨memory,[],none,false,false⟩,.enter callId => some ⟨memory,[],some callId,true,false⟩
  | ⟨memory,[],some callId,true,false⟩,.arm receipt => some ⟨memory,recipe memory receipt,some callId,true,false⟩
  | ⟨memory,store::rest,some callId,true,false⟩,.commit => some ⟨write memory store,rest,some callId,true,false⟩
  | ⟨memory,[],some _,true,false⟩,.returnCall => some ⟨memory,[],none,false,false⟩
  | ⟨memory,pending,call,gate,false⟩,.retire => some ⟨memory,pending,call,gate,true⟩
  | ⟨memory,pending,some _,true,true⟩,.releaseRetired => some ⟨memory,pending,none,false,true⟩
  | _,_ => none

theorem advance_exact : advance s action = some next ↔ Step s action next := by
  constructor
  · intro checked
    rcases s with ⟨memory,pending,call,gate,retired⟩
    cases pending <;> cases call <;> cases gate <;> cases retired <;> cases action <;>
      simp only [advance] at checked <;> try contradiction
    all_goals cases Option.some.inj checked; constructor
  · intro step
    cases step with
    | retire =>
        rename_i memory pending call gate
        cases pending <;> cases call <;> cases gate <;> rfl
    | releaseRetired =>
        rename_i memory pending callId
        cases pending <;> rfl
    | enter => rfl
    | arm => rfl
    | commit => rfl
    | returnCall => rfl

def WellFormed (s : State p a) : Prop :=
  (s.gate = true ↔ s.call.isSome = true) ∧
  (s.retired = false → s.gate = false → s.pending = [])

theorem preserves (valid : WellFormed s) (step : Step s action next) : WellFormed next := by
  cases step <;> simp_all [WellFormed]

def target (s : State p a) : Memory p a := s.pending.foldl write s.memory

theorem commit_target (step : Step s .commit next) : target next = target s := by
  cases step; rfl

theorem retire_retains (step : Step s .retire next) :
    next.memory = s.memory ∧ next.pending = s.pending ∧ target next = target s := by
  cases step; exact ⟨rfl,rfl,rfl⟩

theorem cleanup_retains (step : Step s .releaseRetired next) :
    next.memory = s.memory ∧ next.pending = s.pending ∧ next.retired = true ∧
    next.gate = false ∧ next.call = none := by
  cases step; exact ⟨rfl,rfl,rfl,rfl,rfl⟩

theorem return_discharged (step : Step s .returnCall next) :
    s.pending = [] ∧ s.retired = false ∧ next.memory = s.memory := by
  cases step; exact ⟨rfl,rfl,rfl⟩

theorem stopped_no_commit (stopped : s.retired = true) : advance s .commit = none := by
  rcases s with ⟨memory,pending,call,gate,retired⟩
  cases retired <;> simp_all
  cases pending <;> cases call <;> cases gate <;> rfl

theorem stopped_no_entry (stopped : s.retired = true) : advance s (.enter callId) = none := by
  rcases s with ⟨memory,pending,call,gate,retired⟩
  cases retired <;> simp_all
  cases pending <;> cases call <;> cases gate <;> rfl

theorem stopped_no_arm (stopped : s.retired = true) : advance s (.arm receipt) = none := by
  rcases s with ⟨memory,pending,call,gate,retired⟩
  cases retired <;> simp_all
  cases pending <;> cases call <;> cases gate <;> rfl

theorem retired_monotone (step : Step s action next) (stopped : s.retired = true) :
    next.retired = true := by
  cases step <;> simp_all

-- Completed outer calls may retain protocol notification debt. This is an
-- explicit positive path; requiring all payment debt empty here would reject
-- the selected public-owner protocol even when all local stores are done.
theorem payment_can_survive_return (memory : Memory p a) (payment : PaidHeadPhase.Pending p)
    (callId : Nat) :
    Step ⟨{memory with pendingPayment:=some payment},[],some callId,true,false⟩ .returnCall
      ⟨{memory with pendingPayment:=some payment},[],none,false,false⟩ := .returnCall

inductive Runs (base : State p a) : State p a → Prop where
  | nil : Runs base base
  | step : Runs base s → Step s action next → Runs base next

theorem Runs.trans (left : Runs base middle) (right : Runs middle after) : Runs base after := by
  induction right with
  | nil => exact left
  | step path step ih => exact .step ih step

theorem discharge (memory : Memory p a) (pending : List (Store p a)) (callId : Nat) :
    Runs ⟨memory,pending,some callId,true,false⟩
      ⟨pending.foldl write memory,[],some callId,true,false⟩ := by
  induction pending generalizing memory with
  | nil => exact .nil
  | cons store rest ih => exact (Runs.step Runs.nil Step.commit).trans (ih (write memory store))

theorem normal_recipe (memory : Memory p a) (receipt : Receipt p a) (callId : Nat) :
    Runs ⟨memory,[],some callId,true,false⟩
      ⟨(recipe memory receipt).foldl write memory,[],none,false,false⟩ := by
  exact (Runs.step Runs.nil Step.arm).trans ((discharge memory (recipe memory receipt) callId).trans
    (Runs.step Runs.nil Step.returnCall))

-- General mixed initialization prefix. This is parameterized by any actual
-- owner/image and before memory with that owner not yet marked. Its native
-- authenticity is bound by initialized_revision_zero, not by decide on a fixture.
theorem mixed_initialization (before : Memory p a) (owner : Fin p) (image : OwnerImage.Image p a)
    (fresh : owner ∉ before.initialized) (callId : Nat) :
    let mixed := write before (.initialized owner)
    Runs ⟨before,[],some callId,true,false⟩
      ⟨mixed,[.installed owner 0],none,false,true⟩ := by
  dsimp only
  have arm : Step ⟨before,[],some callId,true,false⟩
      (.arm (.ownerReturned owner (.owner (.initialize image)) (.inl 10) none))
      ⟨before,[.initialized owner,.installed owner 0],some callId,true,false⟩ := by
    simpa [recipe,ownerStores,fresh] using
      (Step.arm (memory:=before) (callId:=callId)
        (receipt:=Receipt.ownerReturned owner (.owner (.initialize image)) (.inl 10) none))
  exact (((Runs.step Runs.nil arm).step Step.commit).step Step.retire).step Step.releaseRetired

#print axioms initialized_revision_zero
#print axioms advance_exact
#print axioms preserves
#print axioms commit_target
#print axioms retire_retains
#print axioms cleanup_retains
#print axioms return_discharged
#print axioms stopped_no_commit
#print axioms stopped_no_entry
#print axioms stopped_no_arm
#print axioms retired_monotone
#print axioms payment_can_survive_return
#print axioms discharge
#print axioms normal_recipe
#print axioms mixed_initialization
end MirroreaProofFirst.CohortCommitJournal
