import MirroreaProofFirstReferenceCancellation

namespace MirroreaProofFirst.ReferenceStore
open ReferenceOwner ReferenceAccessHistory

inductive Occurrence where
  | core (event : CompositionMachine.Occurrence)
  | binding (context : ReferenceOwner.Context)
  | cancellation (permit : ReferenceCancellation.Permit)
  deriving DecidableEq, Repr

structure Machine (p a : Nat) where
  core : CompositionMachine.Machine p a
  bindings : List (Option Binding)
  history : List (Frame p a)
  events : List Occurrence

def frame (core : CompositionMachine.Machine p a) : Frame p a :=
  ⟨core.system,core.system.controlPolicy 13⟩

def Floor (s : InstanceState.State d p n) (row : Option Binding) : Prop :=
  ∀ binding, row = some binding → FallbackStatic.Admissible s binding.request.chain
def floorCheck (s : InstanceState.State d p n) : Option Binding → Bool
  | none => true
  | some binding => match FallbackStatic.check s binding.request.chain with | .ok _ => true | .error _ => false

theorem floor_exact (s : InstanceState.State d p n) (row : Option Binding) : floorCheck s row = true ↔ Floor s row := by
  cases row with
  | none => simp [floorCheck,Floor]
  | some binding =>
      have admitted := FallbackStatic.check_exact s binding.request.chain
      cases h : FallbackStatic.check s binding.request.chain with
      | error reason => simp [h] at admitted; simp [floorCheck,Floor,h,admitted]
      | ok value => cases value; simp [h] at admitted; simp [floorCheck,Floor,h,admitted]

def Floors (s : InstanceState.State d p n) (rows : List (Option Binding)) : Prop :=
  ∀ row ∈ rows, Floor s row
def floorsCheck (s : InstanceState.State d p n) (rows : List (Option Binding)) : Bool := rows.all (floorCheck s)

theorem floors_exact (s : InstanceState.State d p n) (rows : List (Option Binding)) :
    floorsCheck s rows = true ↔ Floors s rows := by simp [floorsCheck,Floors,List.all_eq_true,floor_exact]

def coreEvents (events : List Occurrence) : List CompositionMachine.Occurrence :=
  events.filterMap fun event => match event with | .core e => some e | .binding _ => none | .cancellation permit => some (.cancelled permit.core)

def Invariant (m : Machine p a) : Prop :=
  CompositionMachine.Invariant m.core ∧ CatalogHistory.Invariant m.core.system.configuration ∧
  Floors m.core.system.configuration.state m.bindings ∧
  (∃ past, m.history = past ++ [frame m.core]) ∧ coreEvents m.events = m.core.events

-- Fresh construction only: no entry imports an arbitrary populated core while
-- dropping its bindings/history. Current authority is an explicit environment
-- input, not generated by typing or this constructor. No restore claim here.
def initial (realm : Nat) (view : WorldProjection.AuthorityView a) (policy : Nat → CurrentUse.Policy) : Machine p a :=
  let state : InstanceState.State 0 p 0 :=
    ⟨realm,fun _ => 0,Fin.elim0,Fin.elim0,Fin.elim0,fun _ => true⟩
  let core : CompositionMachine.Machine p a :=
    ⟨⟨CompositionCore.config state,view,policy,0,[]⟩,[],[]⟩
  ⟨core,[],[frame core],[]⟩

theorem initial_invariant (realm : Nat) (view : WorldProjection.AuthorityView a) (policy : Nat → CurrentUse.Policy) :
    Invariant (initial (p:=p) realm view policy) := by
  have catalog := CatalogHistory.empty_valid
    (⟨realm,fun _ => 0,Fin.elim0,Fin.elim0,Fin.elim0,fun _ => true⟩ : InstanceState.State 0 p 0)
  refine ⟨⟨⟨catalog.toValid,by simp [initial]⟩,by simp [initial],by simp [initial]⟩,catalog,?_,⟨[],rfl⟩,rfl⟩
  simp [initial,Floors]

-- Every actual semantic entry appends the resulting frame. These full finite
-- images are a nonproduction currentness representation, not a persistence API.
def advanceCore (m : Machine p a) (next : CompositionMachine.Machine p a)
    (event : CompositionMachine.Occurrence) : Machine p a :=
  {m with core := next,history := m.history ++ [frame next],events := .core event :: m.events}

theorem advanceCore_preserves (m : Machine p a) (next : CompositionMachine.Machine p a)
    (event : CompositionMachine.Occurrence) (valid : Invariant m)
    (core : CompositionMachine.Invariant next) (step : CatalogHistory.Transition m.core next)
    (floor : Floors next.system.configuration.state m.bindings)
    (actualEvent : next.events = event :: m.core.events) : Invariant (advanceCore m next event) := by
  refine ⟨core,(CatalogHistory.transition_catalog _ _ valid.2.1 step).1,floor,⟨m.history,rfl⟩,?_⟩
  simpa [advanceCore,coreEvents,← valid.2.2.2.2] using actualEvent.symm

-- The floor test is on the tentative result of ONE real authorized core
-- operation. Rejection commits neither that operation nor a fabricated event.
def manage (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (raw : CompositionCore.Raw) : Option (Machine p a × Option Nat) := do
  let (next,created) ← CompositionMachine.manage m.core member place principal id raw
  if floorsCheck next.system.configuration.state m.bindings then
    some (advanceCore m next (.management (ManagementEntry.current m.core.system member place principal id raw) created),created)
  else none

theorem manage_parts (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (raw : CompositionCore.Raw) (result : Machine p a × Option Nat)
    (accepted : manage m member place principal id raw = some result) :
    ∃ next created, CompositionMachine.manage m.core member place principal id raw = some (next,created) ∧
      Floors next.system.configuration.state m.bindings ∧
      result = (advanceCore m next (.management (ManagementEntry.current m.core.system member place principal id raw) created),created) := by
  unfold manage at accepted
  cases hr : CompositionMachine.manage m.core member place principal id raw with
  | none => simp [hr] at accepted
  | some pair =>
      obtain ⟨next,created⟩ := pair
      simp only [hr,Option.bind_eq_bind,Option.bind_some] at accepted
      split at accepted
      · rename_i checked
        exact ⟨next,created,rfl,(floors_exact _ _).mp checked,(Option.some.inj accepted).symm⟩
      · cases accepted

theorem manage_preserves (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (raw : CompositionCore.Raw) (result : Machine p a × Option Nat) (valid : Invariant m)
    (accepted : manage m member place principal id raw = some result) :
    Invariant result.1 ∧ result.1.bindings = m.bindings ∧
      ∃ current, result.1.history = m.history ++ [current] := by
  obtain ⟨next,created,coreRun,floor,rfl⟩ := manage_parts _ _ _ _ _ _ _ accepted
  have actualEvent : next.events = .management (ManagementEntry.current m.core.system member place principal id raw) created :: m.core.events := by
    obtain ⟨_,e,cfg,created',_,_,eq⟩ := CompositionMachine.manage_parts _ _ _ _ _ _ _ coreRun
    cases eq
    rfl
  exact ⟨advanceCore_preserves _ _ _ valid (CompositionMachine.manage_preserves _ _ _ _ _ _ _ valid.1 coreRun)
    (.management coreRun) floor actualEvent,rfl,⟨_,rfl⟩⟩

theorem manage_complete (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (raw : CompositionCore.Raw) (next : CompositionMachine.Machine p a) (created : Option Nat)
    (coreRun : CompositionMachine.manage m.core member place principal id raw = some (next,created))
    (floor : Floors next.system.configuration.state m.bindings) :
    ∃ result, manage m member place principal id raw = some result := by
  simp [manage,coreRun,(floors_exact _ _).mpr floor]

def authorityHead (m : Machine p a) (view : WorldProjection.AuthorityView a) : Machine p a :=
  advanceCore m (CompositionMachine.authorityHead m.core view) (.authorityHead view.generation)

theorem authorityHead_preserves (m : Machine p a) (view : WorldProjection.AuthorityView a) (valid : Invariant m) :
    Invariant (authorityHead m view) ∧ (authorityHead m view).bindings = m.bindings ∧
      (authorityHead m view).history = m.history ++ [frame (CompositionMachine.authorityHead m.core view)] := by
  exact ⟨advanceCore_preserves _ _ _ valid (CompositionMachine.head_preserves _ _ valid.1)
    .authority valid.2.2.1 rfl,rfl,rfl⟩

-- A start adds an actual request occurrence. The duplicated system frame is
-- harmless and keeps history/event correspondence explicit; serial need not move.
def start (m : Machine p a) (member : Fin a) (place : Fin p) (principal id key : Nat) (argument : Int) :
    Option (Machine p a × InvocationBoundary.Ticket) := do
  let (next,ticket) ← CompositionMachine.start m.core member place principal id key argument
  return (advanceCore m next (.requested ticket),ticket)

theorem start_preserves (m : Machine p a) (member : Fin a) (place : Fin p) (principal id key : Nat) (argument : Int)
    (result : Machine p a × InvocationBoundary.Ticket) (valid : Invariant m)
    (accepted : start m member place principal id key argument = some result) :
    Invariant result.1 ∧ result.1.bindings = m.bindings ∧ ∃ current, result.1.history = m.history ++ [current] := by
  unfold start at accepted
  cases hr : CompositionMachine.start m.core member place principal id key argument with
  | none => simp [hr] at accepted
  | some pair =>
      obtain ⟨next,ticket⟩ := pair
      simp only [hr,Option.bind_eq_bind,Option.bind_some,Option.pure_def,Option.some.injEq] at accepted
      subst result
      have nextEq := (CompositionMachine.start_parts _ _ _ _ _ _ _ _ hr).2.2
      change next = CompositionMachine.enqueue m.core ticket at nextEq
      have floor : Floors next.system.configuration.state m.bindings := by rw [nextEq]; exact valid.2.2.1
      have actualEvent : next.events = .requested ticket :: m.core.events := by rw [nextEq]; rfl
      exact ⟨advanceCore_preserves _ _ _ valid (CompositionMachine.start_preserves _ _ _ _ _ _ _ _ valid.1 hr)
        (.request hr) floor actualEvent,rfl,⟨_,rfl⟩⟩

-- Lower core-ticket helper. The admitted ReferenceExecution entry checks its
-- total saved classification and continuous reference/holding protection first.
-- This helper alone is not an admitted source or protected-engine transition.
def finishPlain (m : Machine p a) (ticket : InvocationBoundary.Ticket) (value : Int) : Option (Machine p a) := do
  let next ← CompositionMachine.finish m.core ticket value
  return advanceCore m next (.result ticket value)

theorem finishPlain_preserves (m : Machine p a) (ticket : InvocationBoundary.Ticket) (value : Int)
    (result : Machine p a) (valid : Invariant m) (accepted : finishPlain m ticket value = some result) :
    Invariant result ∧ result.bindings = m.bindings ∧ ∃ current, result.history = m.history ++ [current] := by
  unfold finishPlain at accepted
  cases hr : CompositionMachine.finish m.core ticket value with
  | none => simp [hr] at accepted
  | some next =>
      simp only [hr,Option.bind_eq_bind,Option.bind_some,Option.pure_def,Option.some.injEq] at accepted
      subst result
      have nextEq := (CompositionMachine.finish_parts _ _ _ _ hr).2.2.2
      have floor : Floors next.system.configuration.state m.bindings := by rw [nextEq]; exact valid.2.2.1
      have actualEvent : next.events = .result ticket value :: m.core.events := by rw [nextEq]; rfl
      exact ⟨advanceCore_preserves _ _ _ valid (CompositionMachine.finish_preserves _ _ _ _ valid.1 hr)
        (.result hr) floor actualEvent,rfl,⟨_,rfl⟩⟩

def cancelled (m : Machine p a) (next : CompositionMachine.Machine p a)
    (permit : ReferenceCancellation.Permit) : Machine p a :=
  {m with core := next,history := m.history ++ [frame next],events := .cancellation permit :: m.events}

def cancel (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (entry : ReferenceExecution.Pending) (permit : ReferenceCancellation.Permit) : Option (Machine p a) := do
  if !ReferenceCancellation.check m.core.system m.core.events.length m.events.length entry member place principal id permit then none else do
    let next ← CompositionMachine.cancel m.core member place principal id entry.ticket permit.core
    return cancelled m next permit

theorem cancel_parts (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (entry : ReferenceExecution.Pending) (permit : ReferenceCancellation.Permit) (result : Machine p a)
    (accepted : cancel m member place principal id entry permit = some result) :
    ReferenceCancellation.Submitted m.core.system m.core.events.length m.events.length entry member place principal id permit ∧
      ∃ next, CompositionMachine.cancel m.core member place principal id entry.ticket permit.core = some next ∧
        result = cancelled m next permit := by
  unfold cancel at accepted
  split at accepted
  · cases accepted
  · rename_i checked
    have yes : ReferenceCancellation.check m.core.system m.core.events.length m.events.length entry member place principal id permit = true := by simpa using checked
    cases run : CompositionMachine.cancel m.core member place principal id entry.ticket permit.core with
    | none => simp [run] at accepted
    | some next =>
        simp only [run,Option.bind_eq_bind,Option.bind_some,Option.pure_def,Option.some.injEq] at accepted
        exact ⟨(ReferenceCancellation.check_exact _ _ _ _ _ _ _ _ _).mp yes,next,rfl,accepted.symm⟩

theorem cancel_preserves (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (entry : ReferenceExecution.Pending) (permit : ReferenceCancellation.Permit) (result : Machine p a)
    (valid : Invariant m) (accepted : cancel m member place principal id entry permit = some result) :
    Invariant result ∧ result.bindings = m.bindings ∧ ∃ current, result.history = m.history ++ [current] := by
  obtain ⟨_,next,run,rfl⟩ := cancel_parts _ _ _ _ _ _ _ _ accepted
  have core := CompositionMachine.cancel_preserves _ _ _ _ _ _ _ _ valid.1 run
  obtain ⟨_,_,_,_,rfl⟩ := CompositionMachine.cancel_parts _ _ _ _ _ _ _ _ run
  refine ⟨⟨core,valid.2.1,valid.2.2.1,⟨m.history,rfl⟩,?_⟩,rfl,⟨_,rfl⟩⟩
  simpa [cancelled,coreEvents,CompositionMachine.abandon] using valid.2.2.2.2

#print axioms cancel_preserves
#print axioms floor_exact
#print axioms floors_exact
#print axioms advanceCore_preserves
#print axioms manage_preserves
#print axioms manage_complete
#print axioms authorityHead_preserves
#print axioms start_preserves
#print axioms finishPlain_preserves
#print axioms initial_invariant
end MirroreaProofFirst.ReferenceStore
