import Std

/- Task-local research, not a Canon carrier or production interface.
   Binary positive syntax; list all/any will be represented by folds.
   No authority is generated by support. Eligibility is an explicit parameter. -/
namespace MirroreaProofFirst.Support

inductive Formula (K : Type) where
  | top | bottom | ref (key : K)
  | both (left right : Formula K)
  | either (left right : Formula K)
  deriving Repr

def Holds (available : K → Prop) : Formula K → Prop
  | .top => True
  | .bottom => False
  | .ref k => available k
  | .both p q => Holds available p ∧ Holds available q
  | .either p q => Holds available p ∨ Holds available q

def eval (available : K → Bool) : Formula K → Bool
  | .top => true
  | .bottom => false
  | .ref k => available k
  | .both p q => eval available p && eval available q
  | .either p q => eval available p || eval available q

theorem eval_correct (available : K → Bool) (f : Formula K) :
    eval available f = true ↔ Holds (fun k => available k = true) f := by
  induction f with
  | top => simp [eval, Holds]
  | bottom => simp [eval, Holds]
  | ref k => rfl
  | both p q hp hq => simp [eval, Holds, hp, hq]
  | either p q hp hq => simp [eval, Holds, hp, hq]

theorem holds_mono {A B : K → Prop} (h : ∀ k, A k → B k)
    (f : Formula K) : Holds A f → Holds B f := by
  induction f with
  | top => exact id
  | bottom => exact False.elim
  | ref k => exact h k
  | both p q hp hq => exact fun v => ⟨hp v.1, hq v.2⟩
  | either p q hp hq => exact fun v => v.elim (fun x => Or.inl (hp x)) (fun x => Or.inr (hq x))

/- Declarative finite proof trees. This definition does not mention iteration,
   a certificate, a checker verdict, or a stored invariant. -/
inductive Proof (forms : K → Formula K) (eligible : K → Prop) : Formula K → Prop where
  | root : Proof forms eligible .top
  | reference : eligible k → Proof forms eligible (forms k) → Proof forms eligible (.ref k)
  | conjunction : Proof forms eligible p → Proof forms eligible q → Proof forms eligible (.both p q)
  | left : Proof forms eligible p → Proof forms eligible (.either p q)
  | right : Proof forms eligible q → Proof forms eligible (.either p q)

def Grounded (forms : K → Formula K) (eligible : K → Prop) (k : K) : Prop :=
  eligible k ∧ Proof forms eligible (forms k)

def Closed (forms : K → Formula K) (eligible C : K → Prop) : Prop :=
  ∀ k, eligible k → Holds C (forms k) → C k

theorem proof_in_closed {forms : K → Formula K} {eligible C : K → Prop}
    (hc : Closed forms eligible C) {f : Formula K} (hp : Proof forms eligible f) :
    Holds C f := by
  induction hp with
  | root => trivial
  | reference he _ ih => exact hc _ he ih
  | conjunction _ _ hp hq => exact ⟨hp, hq⟩
  | left _ hp => exact Or.inl hp
  | right _ hq => exact Or.inr hq

theorem holds_to_proof {forms : K → Formula K} {eligible : K → Prop}
    (f : Formula K) : Holds (Grounded forms eligible) f → Proof forms eligible f := by
  induction f with
  | top => exact fun _ => .root
  | bottom => exact False.elim
  | ref k => exact fun h => .reference h.1 h.2
  | both p q hp hq => exact fun h => .conjunction (hp h.1) (hq h.2)
  | either p q hp hq => exact fun h => h.elim (fun x => .left (hp x)) (fun x => .right (hq x))

theorem grounded_closed (forms : K → Formula K) (eligible : K → Prop) :
    Closed forms eligible (Grounded forms eligible) := by
  intro k he h
  exact ⟨he, holds_to_proof _ h⟩

theorem grounded_least {forms : K → Formula K} {eligible C : K → Prop}
    (hc : Closed forms eligible C) : ∀ k, Grounded forms eligible k → C k := by
  intro k h
  exact hc k h.1 (proof_in_closed hc h.2)

/- Membership certificate, deliberately separate from canonical earliest rank.
   Every live member has a finite rank and earlier justification; excluded
   derivable eligible nodes cannot be silently omitted. -/
def Ranked (forms : K → Formula K) (eligible C : K → Prop) (rank : K → Nat) : Prop :=
  (∀ k, C k → eligible k) ∧
  (∀ k, C k → Holds (fun j => C j ∧ rank j < rank k) (forms k)) ∧
  Closed forms eligible C

theorem ranked_sound {forms : K → Formula K} {eligible C : K → Prop}
    {rank : K → Nat} (cert : Ranked forms eligible C rank) :
    ∀ k, C k → Grounded forms eligible k := by
  have ranked_induction : ∀ n k, rank k = n → C k → Grounded forms eligible k := by
    intro n
    induction n using Nat.strongRecOn with
    | ind n ih =>
      intro k hk hc
      apply grounded_closed forms eligible k (cert.1 k hc)
      apply holds_mono (fun j (hj : C j ∧ rank j < rank k) => ih (rank j) (hk ▸ hj.2) j rfl hj.1) (forms k)
      exact cert.2.1 k hc
  intro k hc
  exact ranked_induction (rank k) k rfl hc

theorem ranked_exact {forms : K → Formula K} {eligible C : K → Prop}
    {rank : K → Nat} (cert : Ranked forms eligible C rank) :
    ∀ k, C k ↔ Grounded forms eligible k := by
  intro k
  exact ⟨ranked_sound cert k, grounded_least cert.2.2 k⟩

def rounds (forms : K → Formula K) (eligible : K → Bool) : Nat → K → Bool
  | 0 => fun _ => false
  | n+1 => fun k => rounds forms eligible n k ||
      (eligible k && eval (rounds forms eligible n) (forms k))

theorem rounds_step (forms : K → Formula K) (eligible : K → Bool) (n : Nat) :
    ∀ k, rounds forms eligible n k = true → rounds forms eligible (n+1) k = true := by
  intro k h
  simp [rounds, h]

theorem rounds_mono (forms : K → Formula K) (eligible : K → Bool)
    {n m : Nat} (h : n ≤ m) :
    ∀ k, rounds forms eligible n k = true → rounds forms eligible m k = true := by
  induction h with
  | refl => exact fun _ h => h
  | step h ih => exact fun k hk => rounds_step forms eligible _ k (ih k hk)

theorem eval_rounds_mono (forms : K → Formula K) (eligible : K → Bool)
    {n m : Nat} (h : n ≤ m) (f : Formula K) :
    eval (rounds forms eligible n) f = true → eval (rounds forms eligible m) f = true := by
  intro hf
  exact (eval_correct _ _).mpr (holds_mono (rounds_mono forms eligible h) f ((eval_correct _ _).mp hf))

theorem rounds_sound (forms : K → Formula K) (eligible : K → Bool) (n : Nat) :
    ∀ k, rounds forms eligible n k = true → Grounded forms (fun j => eligible j = true) k := by
  induction n with
  | zero => simp [rounds]
  | succ n ih =>
    intro k hk
    simp only [rounds, Bool.or_eq_true, Bool.and_eq_true] at hk
    cases hk with
    | inl h => exact ih k h
    | inr h =>
      exact grounded_closed forms _ k h.1
        (holds_mono ih _ ((eval_correct _ _).mp h.2))

theorem proof_eventually {forms : K → Formula K} {eligible : K → Bool}
    {f : Formula K} (hp : Proof forms (fun j => eligible j = true) f) :
    ∃ n, eval (rounds forms eligible n) f = true := by
  induction hp with
  | root => exact ⟨0, rfl⟩
  | reference he _ ih =>
    obtain ⟨n, hn⟩ := ih
    exact ⟨n+1, by simp [eval, rounds, he, hn]⟩
  | conjunction _ _ hp hq =>
    obtain ⟨n, hn⟩ := hp
    obtain ⟨m, hm⟩ := hq
    exact ⟨max n m, by
      simp only [eval, Bool.and_eq_true]
      exact ⟨eval_rounds_mono forms eligible (Nat.le_max_left n m) _ hn,
        eval_rounds_mono forms eligible (Nat.le_max_right n m) _ hm⟩⟩
  | left _ ih =>
    obtain ⟨n, hn⟩ := ih
    exact ⟨n, by simp [eval, hn]⟩
  | right _ ih =>
    obtain ⟨n, hn⟩ := ih
    exact ⟨n, by simp [eval, hn]⟩

theorem rounds_complete {forms : K → Formula K} {eligible : K → Bool} {k : K}
    (h : Grounded forms (fun j => eligible j = true) k) :
    ∃ n, rounds forms eligible n k = true := by
  obtain ⟨n, hn⟩ := proof_eventually h.2
  exact ⟨n+1, by simp [rounds, h.1, hn]⟩

theorem rounds_iff_derivation (forms : K → Formula K) (eligible : K → Bool) (k : K) :
    (∃ n, rounds forms eligible n k = true) ↔ Grounded forms (fun j => eligible j = true) k := by
  exact ⟨fun ⟨n, h⟩ => rounds_sound forms eligible n k h, rounds_complete⟩

def allOf : List (Formula K) → Formula K
  | [] => .top
  | p :: ps => .both p (allOf ps)

def anyOf : List (Formula K) → Formula K
  | [] => .bottom
  | p :: ps => .either p (anyOf ps)

theorem allOf_correct (A : K → Prop) (fs : List (Formula K)) :
    Holds A (allOf fs) ↔ ∀ f ∈ fs, Holds A f := by
  induction fs with
  | nil => simp [allOf, Holds]
  | cons f fs ih => simp [allOf, Holds, ih]

theorem anyOf_correct (A : K → Prop) (fs : List (Formula K)) :
    Holds A (anyOf fs) ↔ ∃ f ∈ fs, Holds A f := by
  induction fs with
  | nil => simp [anyOf, Holds]
  | cons f fs ih => simp [anyOf, Holds, ih]

/- Counting lemma over an explicit complete universe; duplicate-free enumeration
   is not needed for this length bound (but gives the cardinality bound). -/
theorem filter_count_mono (xs : List K) (a b : K → Bool)
    (h : ∀ k ∈ xs, a k = true → b k = true) :
    (xs.filter a).length ≤ (xs.filter b).length := by
  induction xs with
  | nil => simp
  | cons k xs ih =>
    have ht := ih (fun j hj => h j (by simp [hj]))
    have hk := h k (by simp)
    cases ha : a k <;> cases hb : b k <;> simp_all
    omega

theorem equal_filter_count (xs : List K) (a b : K → Bool)
    (h : ∀ k ∈ xs, a k = true → b k = true)
    (hc : (xs.filter a).length = (xs.filter b).length) :
    ∀ k ∈ xs, a k = b k := by
  induction xs with
  | nil => simp
  | cons j xs ih =>
    have ht : ∀ k ∈ xs, a k = true → b k = true := fun k hk => h k (by simp [hk])
    have hl := filter_count_mono xs a b ht
    have hj := h j (by simp)
    cases ha : a j <;> cases hb : b j <;> simp_all
    omega

def countLive (nodes : List K) (forms : K → Formula K) (eligible : K → Bool) (n : Nat) : Nat :=
  (nodes.filter (rounds forms eligible n)).length

theorem changed_grows (nodes : List K) (complete : ∀ k, k ∈ nodes)
    (forms : K → Formula K) (eligible : K → Bool) (n : Nat)
    (changed : rounds forms eligible n ≠ rounds forms eligible (n+1)) :
    countLive nodes forms eligible n < countLive nodes forms eligible (n+1) := by
  have hm := filter_count_mono nodes (rounds forms eligible n) (rounds forms eligible (n+1))
    (fun k _ => rounds_step forms eligible n k)
  have hne : countLive nodes forms eligible n ≠ countLive nodes forms eligible (n+1) := by
    intro heq
    apply changed
    funext k
    exact equal_filter_count nodes _ _ (fun k _ => rounds_step forms eligible n k) heq k (complete k)
  exact Nat.lt_of_le_of_ne hm hne

theorem stable_exists (nodes : List K) (complete : ∀ k, k ∈ nodes)
    (forms : K → Formula K) (eligible : K → Bool) :
    ∃ n, n ≤ nodes.length ∧ rounds forms eligible n = rounds forms eligible (n+1) := by
  classical
  apply Classical.byContradiction
  intro hn
  have changed : ∀ n, n ≤ nodes.length → rounds forms eligible n ≠ rounds forms eligible (n+1) := by
    intro n h hEq
    exact hn ⟨n, h, hEq⟩
  have grow : ∀ n, n ≤ nodes.length+1 → n ≤ countLive nodes forms eligible n := by
    intro n
    induction n with
    | zero => exact fun _ => Nat.zero_le _
    | succ n ih =>
      intro h
      have hp := ih (by omega)
      have hs := changed_grows nodes complete forms eligible n (changed n (by omega))
      omega
  have lo := grow (nodes.length+1) (Nat.le_refl _)
  have hi := List.length_filter_le (rounds forms eligible (nodes.length+1)) nodes
  unfold countLive at lo
  omega

theorem stable_closed (forms : K → Formula K) (eligible : K → Bool) (n : Nat)
    (stable : rounds forms eligible n = rounds forms eligible (n+1)) :
    Closed forms (fun k => eligible k = true) (fun k => rounds forms eligible n k = true) := by
  intro k he hf
  have hn : rounds forms eligible (n+1) k = true := by
    simp [rounds, he, (eval_correct _ _).mpr hf]
  rw [← stable] at hn
  exact hn

theorem bounded_rounds_exact (nodes : List K) (complete : ∀ k, k ∈ nodes)
    (forms : K → Formula K) (eligible : K → Bool) (k : K) :
    rounds forms eligible nodes.length k = true ↔ Grounded forms (fun j => eligible j = true) k := by
  constructor
  · exact rounds_sound forms eligible nodes.length k
  · intro hg
    obtain ⟨n, hn, hs⟩ := stable_exists nodes complete forms eligible
    exact rounds_mono forms eligible hn k (grounded_least (stable_closed forms eligible n hs) k hg)

def derive (nodes : List K) (forms : K → Formula K) (eligible : K → Bool) : List K :=
  nodes.filter (rounds forms eligible nodes.length)

theorem derive_exact (nodes : List K) (complete : ∀ k, k ∈ nodes)
    (forms : K → Formula K) (eligible : K → Bool) (k : K) :
    k ∈ derive nodes forms eligible ↔ Grounded forms (fun j => eligible j = true) k := by
  simp [derive, List.mem_filter, complete, bounded_rounds_exact nodes complete forms eligible k]

/- Actual executable checker of membership certificates. Canonical minimal rank
   equations and input decoder/resource validation are separate obligations. -/
def checkMembership (nodes : List K) (forms : K → Formula K)
    (eligible live : K → Bool) (rank : K → Nat) : Bool :=
  nodes.all fun k =>
    (!live k || eligible k) &&
    (!live k || eval (fun j => live j && decide (rank j < rank k)) (forms k)) &&
    (!(eligible k && eval live (forms k)) || live k)

theorem checker_exact (nodes : List K) (complete : ∀ k, k ∈ nodes)
    (forms : K → Formula K) (eligible live : K → Bool) (rank : K → Nat) :
    checkMembership nodes forms eligible live rank = true ↔
      Ranked forms (fun k => eligible k = true) (fun k => live k = true) rank := by
  simp only [checkMembership, List.all_eq_true, Bool.and_eq_true, Bool.or_eq_true,
    eval_correct]
  constructor
  · intro h
    constructor
    · intro k hk
      have he := (h k (complete k)).1.1
      cases he with
      | inl he => simp [hk] at he
      | inr he => exact he
    constructor
    · intro k hk
      have hf := (h k (complete k)).1.2
      cases hf with
      | inl hf => simp [hk] at hf
      | inr hf =>
        apply holds_mono (fun j hj => ?_) (forms k) hf
        simpa using hj
    · intro k he hf
      have hc := (h k (complete k)).2
      rcases hc with hf' | hl
      · have ht := (eval_correct live (forms k)).mpr hf
        simp [he, ht] at hf'
      · exact hl
  · intro h k _
    constructor
    · constructor
      · cases hk : live k with
        | false => exact Or.inl rfl
        | true => exact Or.inr (h.1 k hk)
      · cases hk : live k with
        | false => exact Or.inl rfl
        | true =>
          apply Or.inr
          apply holds_mono (fun j hj => ?_) (forms k) (h.2.1 k hk)
          simpa using hj
    · cases he : eligible k with
      | false => exact Or.inl rfl
      | true =>
        cases hf : eval live (forms k) with
        | false => exact Or.inl rfl
        | true => exact Or.inr (h.2.2 k he ((eval_correct _ _).mp hf))

theorem checked_membership_exact (nodes : List K) (complete : ∀ k, k ∈ nodes)
    (forms : K → Formula K) (eligible live : K → Bool) (rank : K → Nat)
    (h : checkMembership nodes forms eligible live rank = true) :
    ∀ k, live k = true ↔ Grounded forms (fun j => eligible j = true) k :=
  ranked_exact ((checker_exact nodes complete forms eligible live rank).mp h)

theorem proof_eligible_mono {forms : K → Formula K} {E F : K → Prop}
    (h : ∀ k, E k → F k) {f : Formula K} (hp : Proof forms E f) : Proof forms F f := by
  induction hp with
  | root => exact .root
  | reference he _ ih => exact .reference (h _ he) ih
  | conjunction _ _ hp hq => exact .conjunction hp hq
  | left _ hp => exact .left hp
  | right _ hq => exact .right hq

theorem retirement_mono {forms : K → Formula K} {E F : K → Prop}
    (h : ∀ k, E k → F k) : ∀ k, Grounded forms E k → Grounded forms F k := by
  intro k hk
  exact ⟨h k hk.1, proof_eligible_mono h hk.2⟩

theorem proof_normalized {forms : K → Formula K} {E : K → Prop}
    {f : Formula K} (hp : Proof forms E f) : Proof forms (Grounded forms E) f := by
  induction hp with
  | root => exact .root
  | reference he hf ih => exact .reference ⟨he, hf⟩ ih
  | conjunction _ _ hp hq => exact .conjunction hp hq
  | left _ hp => exact .left hp
  | right _ hq => exact .right hq

theorem normalization_idempotent (forms : K → Formula K) (E : K → Prop) (k : K) :
    Grounded forms (Grounded forms E) k ↔ Grounded forms E k := by
  exact ⟨fun h => h.1, fun h => ⟨h, proof_normalized h.2⟩⟩

/- Uniform rootless graph counterexample family, not a fixed finite decide. -/
theorem no_root_no_ground (next : K → K) (E : K → Prop) (k : K) :
    ¬ Grounded (fun j => Formula.ref (next j)) E k := by
  intro h
  have closed : Closed (fun j => Formula.ref (next j)) E (fun _ => False) := by
    intro j _ hj
    exact hj
  exact grounded_least closed k h

def Only (low : K → Prop) : Formula K → Prop
  | .top | .bottom => True
  | .ref k => low k
  | .both p q | .either p q => Only low p ∧ Only low q

theorem eval_low_congr (low : K → Prop) (a b : K → Bool)
    (h : ∀ k, low k → a k = b k) (f : Formula K) (hf : Only low f) :
    eval a f = eval b f := by
  induction f with
  | top => rfl
  | bottom => rfl
  | ref k => exact h k hf
  | both p q hp hq => simp only [eval, hp hf.1, hq hf.2]
  | either p q hp hq => simp only [eval, hp hf.1, hq hf.2]

theorem low_rounds_independent (low : K → Prop) (forms other : K → Formula K)
    (E F : K → Bool) (sameForms : ∀ k, low k → forms k = other k)
    (sameE : ∀ k, low k → E k = F k)
    (closedLow : ∀ k, low k → Only low (forms k)) (n : Nat) :
    ∀ k, low k → rounds forms E n k = rounds other F n k := by
  induction n with
  | zero => exact fun _ _ => rfl
  | succ n ih =>
    intro k hk
    have hf := eval_low_congr low (rounds forms E n) (rounds other F n) ih (forms k) (closedLow k hk)
    simp only [rounds]
    rw [ih k hk, sameE k hk, hf, sameForms k hk]

theorem low_grounded_independent (low : K → Prop) (forms other : K → Formula K)
    (E F : K → Bool) (sameForms : ∀ k, low k → forms k = other k)
    (sameE : ∀ k, low k → E k = F k)
    (closedLow : ∀ k, low k → Only low (forms k)) (k : K) (hk : low k) :
    Grounded forms (fun j => E j = true) k ↔ Grounded other (fun j => F j = true) k := by
  rw [← rounds_iff_derivation, ← rounds_iff_derivation]
  constructor <;> intro ⟨n, hn⟩
  · exact ⟨n, (low_rounds_independent low forms other E F sameForms sameE closedLow n k hk) ▸ hn⟩
  · exact ⟨n, (low_rounds_independent low forms other E F sameForms sameE closedLow n k hk).symm ▸ hn⟩

def firstRank (forms : K → Formula K) (eligible : K → Bool) (k : K) : Nat → Nat
  | 0 => 0
  | n+1 => if rounds forms eligible n k then firstRank forms eligible k n else n

theorem firstRank_spec (forms : K → Formula K) (eligible : K → Bool) (k : K) (bound : Nat)
    (live : rounds forms eligible bound k = true) :
    firstRank forms eligible k bound < bound ∧
    rounds forms eligible (firstRank forms eligible k bound) k = false ∧
    rounds forms eligible (firstRank forms eligible k bound + 1) k = true := by
  induction bound with
  | zero => simp [rounds] at live
  | succ n ih =>
    cases old : rounds forms eligible n k with
    | false => simp only [firstRank, old, Bool.false_eq_true, ↓reduceIte]; exact ⟨by omega, trivial, live⟩
    | true =>
      obtain ⟨hb, hf, ht⟩ := ih old
      simp only [firstRank, old, ↓reduceIte]
      exact ⟨by omega, hf, ht⟩

theorem earlier_iff (forms : K → Formula K) (eligible : K → Bool)
    (bound r : Nat) (hr : r ≤ bound) (k : K) :
    rounds forms eligible r k = true ↔
      rounds forms eligible bound k = true ∧ firstRank forms eligible k bound < r := by
  constructor
  · intro h
    have hl := rounds_mono forms eligible hr k h
    obtain ⟨_, hf, _⟩ := firstRank_spec forms eligible k bound hl
    refine ⟨hl, ?_⟩
    apply Nat.lt_of_not_ge
    intro hn
    have bad := rounds_mono forms eligible hn k h
    simp [hf] at bad
  · intro ⟨hl, hb⟩
    have hs := (firstRank_spec forms eligible k bound hl).2.2
    exact rounds_mono forms eligible (by omega) k hs

theorem generated_ranked (nodes : List K) (complete : ∀ k, k ∈ nodes)
    (forms : K → Formula K) (eligible : K → Bool) :
    Ranked forms (fun k => eligible k = true)
      (fun k => rounds forms eligible nodes.length k = true)
      (fun k => firstRank forms eligible k nodes.length) := by
  constructor
  · intro k hk
    exact (rounds_sound forms eligible nodes.length k hk).1
  constructor
  · intro k hk
    obtain ⟨hb, hf, ht⟩ := firstRank_spec forms eligible k nodes.length hk
    simp only [rounds, hf, Bool.false_or, Bool.and_eq_true] at ht
    apply holds_mono (fun j hj => (earlier_iff forms eligible nodes.length (firstRank forms eligible k nodes.length) (Nat.le_of_lt hb) j).mp hj) (forms k)
    exact (eval_correct _ _).mp ht.2
  · intro k he hf
    apply (bounded_rounds_exact nodes complete forms eligible k).mpr
    apply grounded_closed forms _ k he
    exact holds_mono (fun j hj => (bounded_rounds_exact nodes complete forms eligible j).mp hj) (forms k) hf

theorem generated_certificate_accepted (nodes : List K) (complete : ∀ k, k ∈ nodes)
    (forms : K → Formula K) (eligible : K → Bool) :
    checkMembership nodes forms eligible (rounds forms eligible nodes.length)
      (fun k => firstRank forms eligible k nodes.length) = true :=
  (checker_exact nodes complete forms eligible _ _).mpr (generated_ranked nodes complete forms eligible)

/- Height is shifted relative to Python: top=-1 becomes some0,
   live ref rank r becomes some(r+1), infinity becomes none. -/
def height (live : K → Bool) (rank : K → Nat) : Formula K → Option Nat
  | .top => some 0
  | .bottom => none
  | .ref k => if live k then some (rank k+1) else none
  | .both p q => match height live rank p, height live rank q with
      | some a, some b => some (max a b)
      | _, _ => none
  | .either p q => match height live rank p, height live rank q with
      | none, h | h, none => h
      | some a, some b => some (min a b)

theorem height_threshold (live : K → Bool) (rank : K → Nat) (f : Formula K) (b : Nat) :
    eval (fun j => live j && decide (rank j < b)) f = true ↔
      ∃ h, height live rank f = some h ∧ h ≤ b := by
  induction f with
  | top => simp [eval, height]
  | bottom => simp [eval, height]
  | ref k => cases hk : live k <;> simp [eval, height, hk, Nat.succ_le_iff]
  | both p q hp hq =>
    simp only [eval, Bool.and_eq_true, hp, hq, height]
    cases hh : height live rank p <;> cases hj : height live rank q <;> simp [Nat.max_le]
  | either p q hp hq =>
    simp only [eval, Bool.or_eq_true, hp, hq, height]
    cases hh : height live rank p <;> cases hj : height live rank q <;> simp <;> omega

def checkCanonical (nodes : List K) (forms : K → Formula K)
    (eligible live : K → Bool) (rank : K → Nat) : Bool :=
  checkMembership nodes forms eligible live rank &&
    nodes.all (fun k => !live k || decide (height live rank (forms k) = some (rank k)))

theorem canonical_rounds (forms : K → Formula K) (eligible live : K → Bool) (rank : K → Nat)
    (cert : Ranked forms (fun k => eligible k = true) (fun k => live k = true) rank)
    (heights : ∀ k, live k = true → height live rank (forms k) = some (rank k)) (n : Nat) :
    ∀ k, rounds forms eligible n k = true ↔ live k = true ∧ rank k < n := by
  induction n with
  | zero => simp [rounds]
  | succ n ih =>
    have stateEq : rounds forms eligible n = (fun j => live j && decide (rank j < n)) := by
      funext j
      apply Bool.eq_iff_iff.mpr
      simpa using ih j
    intro k
    constructor
    · intro hk
      have hl := (ranked_exact cert k).mpr (rounds_sound forms eligible (n+1) k hk)
      refine ⟨hl, ?_⟩
      simp only [rounds, Bool.or_eq_true, Bool.and_eq_true] at hk
      cases hk with
      | inl old => have hr := ((ih k).mp old).2; omega
      | inr fresh =>
        rw [stateEq] at fresh
        obtain ⟨h, hh, hb⟩ := (height_threshold live rank (forms k) n).mp fresh.2
        have hEq := heights k hl
        rw [hEq] at hh
        have he : rank k = h := Option.some.inj hh
        omega
    · intro ⟨hl, hr⟩
      have he := cert.1 k hl
      have hv : eval (rounds forms eligible n) (forms k) = true := by
        rw [stateEq]
        exact (height_threshold live rank (forms k) n).mpr ⟨rank k, heights k hl, by omega⟩
      simp [rounds, he, hv]

theorem canonical_rank_unique (nodes : List K) (complete : ∀ k, k ∈ nodes)
    (forms : K → Formula K) (eligible live : K → Bool) (rank : K → Nat)
    (cert : Ranked forms (fun k => eligible k = true) (fun k => live k = true) rank)
    (heights : ∀ k, live k = true → height live rank (forms k) = some (rank k))
    (k : K) (hk : live k = true) : rank k = firstRank forms eligible k nodes.length := by
  have hl : rounds forms eligible nodes.length k = true :=
    (bounded_rounds_exact nodes complete forms eligible k).mpr ((ranked_exact cert k).mp hk)
  obtain ⟨_, hf, ht⟩ := firstRank_spec forms eligible k nodes.length hl
  have upper := ((canonical_rounds forms eligible live rank cert heights _ k).mp ht).2
  have lower : ¬rank k < firstRank forms eligible k nodes.length := by
    intro h
    have bad := (canonical_rounds forms eligible live rank cert heights _ k).mpr ⟨hk, h⟩
    simp [hf] at bad
  omega

theorem generated_heights (nodes : List K) (forms : K → Formula K) (eligible : K → Bool)
    (k : K) (hk : rounds forms eligible nodes.length k = true) :
    height (rounds forms eligible nodes.length) (fun j => firstRank forms eligible j nodes.length)
      (forms k) = some (firstRank forms eligible k nodes.length) := by
  let live := rounds forms eligible nodes.length
  let rank := fun j => firstRank forms eligible j nodes.length
  have stageEq : ∀ b, b ≤ nodes.length → rounds forms eligible b =
      (fun j => live j && decide (rank j < b)) := by
    intro b hb
    funext j
    apply Bool.eq_iff_iff.mpr
    simpa [live, rank] using earlier_iff forms eligible nodes.length b hb j
  obtain ⟨rb, rf, rt⟩ := firstRank_spec forms eligible k nodes.length hk
  have fresh : eligible k = true ∧ eval (rounds forms eligible (rank k)) (forms k) = true := by
    simpa only [rounds, rf, Bool.false_or, Bool.and_eq_true, rank] using rt
  have hv : eval (fun j => live j && decide (rank j < rank k)) (forms k) = true := by
    rw [← stageEq (rank k) (Nat.le_of_lt rb)]
    exact fresh.2
  obtain ⟨h, hh, hb⟩ := (height_threshold live rank (forms k) (rank k)).mp hv
  have lower : ¬ h < rank k := by
    intro less
    have hBound : h ≤ nodes.length := Nat.le_trans hb (Nat.le_of_lt rb)
    have ev : eval (rounds forms eligible h) (forms k) = true := by
      rw [stageEq h hBound]
      exact (height_threshold live rank (forms k) h).mpr ⟨h, hh, Nat.le_refl _⟩
    have early : rounds forms eligible (h+1) k = true := by simp [rounds, fresh.1, ev]
    have bad := rounds_mono forms eligible (Nat.succ_le_of_lt less) k early
    simp only [rank] at bad
    simp [rf] at bad
  have eq : h = rank k := by omega
  rw [eq] at hh
  exact hh

theorem canonical_generated_accepted (nodes : List K) (complete : ∀ k, k ∈ nodes)
    (forms : K → Formula K) (eligible : K → Bool) :
    checkCanonical nodes forms eligible (rounds forms eligible nodes.length)
      (fun k => firstRank forms eligible k nodes.length) = true := by
  simp only [checkCanonical, Bool.and_eq_true, List.all_eq_true]
  constructor
  · exact generated_certificate_accepted nodes complete forms eligible
  · intro k _
    cases hk : rounds forms eligible nodes.length k with
    | false => simp
    | true => simp [generated_heights nodes forms eligible k hk]

theorem canonical_checker_sound (nodes : List K) (complete : ∀ k, k ∈ nodes)
    (forms : K → Formula K) (eligible live : K → Bool) (rank : K → Nat)
    (checked : checkCanonical nodes forms eligible live rank = true) :
    (∀ k, live k = true ↔ Grounded forms (fun j => eligible j = true) k) ∧
    (∀ k, live k = true → rank k = firstRank forms eligible k nodes.length) := by
  simp only [checkCanonical, Bool.and_eq_true, List.all_eq_true] at checked
  have cert := (checker_exact nodes complete forms eligible live rank).mp checked.1
  have heights : ∀ k, live k = true → height live rank (forms k) = some (rank k) := by
    intro k hk
    have h := checked.2 k (complete k)
    simpa [hk] using h
  exact ⟨ranked_exact cert, fun k hk => canonical_rank_unique nodes complete forms eligible live rank cert heights k hk⟩

/- A finite snapshot index prevents missing-domain certificates. An external
   decoder must retain a bijection to exact incarnation-bearing identities;
   this interface establishes coverage only, not that external refinement. -/
structure Snapshot (n : Nat) where
  forms : Fin n → Formula (Fin n)
  eligible : Fin n → Bool

def snapshotLive (s : Snapshot n) : Fin n → Bool :=
  rounds s.forms s.eligible (List.finRange n).length

def snapshotRank (s : Snapshot n) (k : Fin n) : Nat :=
  firstRank s.forms s.eligible k (List.finRange n).length

def checkSnapshot (s : Snapshot n) (live : Fin n → Bool) (rank : Fin n → Nat) : Bool :=
  checkCanonical (List.finRange n) s.forms s.eligible live rank

theorem snapshot_live_exact (s : Snapshot n) (k : Fin n) :
    snapshotLive s k = true ↔ Grounded s.forms (fun j => s.eligible j = true) k :=
  bounded_rounds_exact (List.finRange n) List.mem_finRange s.forms s.eligible k

theorem snapshot_certificate_accepted (s : Snapshot n) :
    checkSnapshot s (snapshotLive s) (snapshotRank s) = true :=
  canonical_generated_accepted (List.finRange n) List.mem_finRange s.forms s.eligible

theorem snapshot_checked_sound (s : Snapshot n) (live : Fin n → Bool) (rank : Fin n → Nat)
    (checked : checkSnapshot s live rank = true) :
    (∀ k, live k = true ↔ Grounded s.forms (fun j => s.eligible j = true) k) ∧
    (∀ k, live k = true → rank k = snapshotRank s k) :=
  canonical_checker_sound (List.finRange n) List.mem_finRange s.forms s.eligible live rank checked

/- Executable positive/falsifier controls; these are not the general proofs. -/
private def rooted : Bool → Formula Bool
  | false => .either .top (.ref true)
  | true => .ref false
private def rootless : Bool → Formula Bool
  | false => .ref true
  | true => .ref false
#guard derive [false, true] rooted (fun _ => true) == [false, true]
#guard derive [false, true] rootless (fun _ => true) == []
#guard checkCanonical [false, true] rooted (fun _ => true) (fun _ => true) (fun k => if k then 1 else 0)
#guard !checkCanonical [false, true] rooted (fun _ => true) (fun _ => false) (fun _ => 0)
#guard !checkCanonical [false, true] rootless (fun _ => true) (fun _ => true) (fun k => if k then 1 else 0)
#guard !checkCanonical [false, true] rooted (fun _ => true) (fun _ => true) (fun k => if k then 8 else 7)
#guard !checkCanonical [false, true] rooted (fun k => k) (fun _ => true) (fun k => if k then 1 else 0)
#guard eval (fun (_ : Bool) => false) (allOf [])
#guard !eval (fun (_ : Bool) => true) (anyOf [])

/- Oracle boundary controls: the raw checker requires coverage; the snapshot
   wrapper must not expose an attacker-selected enumeration. -/
private def uncoveredForms (k : Fin 2) : Formula (Fin 2) :=
  if k == 0 then .ref 1 else .bottom
private def uncoveredRank (k : Fin 2) : Nat := if k == 0 then 1 else 0
#guard checkCanonical [0] uncoveredForms (fun _ => true) (fun _ => true) uncoveredRank
#guard !checkSnapshot (Snapshot.mk uncoveredForms (fun _ => true)) (fun _ => true) uncoveredRank
#guard snapshotLive (Snapshot.mk (fun (_ : Fin 1) => .top) (fun _ => true)) 0
private def revivalForms (k : Fin 2) : Formula (Fin 2) :=
  if k == 0 then .ref 1 else .top
#guard !snapshotLive (Snapshot.mk revivalForms (fun k => k == 0)) 0
#guard snapshotLive (Snapshot.mk revivalForms (fun _ => true)) 0
#guard !snapshotLive (Snapshot.mk revivalForms (fun k => k == 1)) 0
#guard derive [0,0] (fun (_ : Fin 1) => .top) (fun _ => true) == [0,0]

#print axioms eval_correct
#print axioms holds_mono
#print axioms grounded_closed
#print axioms grounded_least
#print axioms ranked_sound
#print axioms ranked_exact
#print axioms rounds_sound
#print axioms proof_eventually
#print axioms rounds_complete
#print axioms rounds_iff_derivation
#print axioms allOf_correct
#print axioms anyOf_correct
#print axioms stable_exists
#print axioms derive_exact
#print axioms checker_exact
#print axioms checked_membership_exact
#print axioms retirement_mono
#print axioms normalization_idempotent
#print axioms no_root_no_ground
#print axioms low_grounded_independent
#print axioms firstRank_spec
#print axioms generated_certificate_accepted
#print axioms height_threshold
#print axioms canonical_rounds
#print axioms canonical_rank_unique
#print axioms generated_heights
#print axioms canonical_generated_accepted
#print axioms canonical_checker_sound
#print axioms snapshot_live_exact
#print axioms snapshot_certificate_accepted
#print axioms snapshot_checked_sound
end MirroreaProofFirst.Support
