import MixedCancelEmbedding
import MixedRequestControls
namespace MirroreaProofFirst.MixedCancelControls
open MixedRequestCore MixedCancelEntry MixedRequestControls
-- Explicit LAB issuer fixture for pure request4 only. No owner action, no
-- authority generated by the embedding or by successful type checking.
def claim : CurrentUse.Claim :=
 {ManagementEntry.Controls.claim with id := 83,actions := [15],targets := [4]}
def supplied (m : Machine 3 1) : Machine 3 1 :=
 {m with system := {m.system with view := {m.system.view with authority :=
  {m.system.view.authority with issued := claim :: m.system.view.authority.issued}}}}
def pending := bothPending.map fun (m,t,saved) => (supplied m,t,saved)
def cancelled := pending.bind fun (m,t,saved) => do
 let permit ← MixedCancellation.authorize m.system m.events.length t 0 0 7 6
 let next ← cancel m 0 0 7 6 t permit
 return (next,t,saved,permit)
#guard cancelled.isSome
#guard (cancelled.map fun (m,_,saved,_) => decide (m.pending = [.owner saved])) = some true
#guard (cancelled.map fun (m,_,_,_) => m.system.used.map CurrentUse.UseId.request) = some [4,6,3,2,1,0]
#guard (cancelled.bind fun (m,t,_,_) => finishPure m t 5).isNone
#guard (cancelled.bind fun (m,t,_,permit) => cancel m 0 0 7 6 t permit).isNone
#guard (cancelled.bind fun (m,_,_,_) => startPure m 0 0 7 4 0 2).isNone
#guard (cancelled.bind fun (m,_,_,_) => startOwner m 0 0 7 6 1 origin [.integer 5]).isNone
#guard (bothPending.bind fun (m,t,_) => MixedCancellation.authorize m.system m.events.length t 0 0 7 6).isNone
#guard (pending.bind fun (m,t,_) => (MixedCancellation.authorize m.system m.events.length t 0 0 7 5).bind fun permit =>
 cancel m 0 0 7 5 t permit).isNone
#guard (pending.bind fun (m,t,_) => (MixedCancellation.authorize m.system m.events.length t 0 0 7 4).bind fun permit =>
 cancel m 0 0 7 4 t permit).isNone
#guard (pending.bind fun (m,t,_) => (MixedCancellation.authorize m.system m.events.length t 0 0 7 6).bind fun permit =>
 cancel m 0 0 8 6 t permit).isNone
#guard (pending.bind fun (m,t,_) => (MixedCancellation.authorize m.system m.events.length t 0 0 7 6).bind fun permit =>
 cancel (authorityHead m {m.system.view with authority := {m.system.view.authority with revoked := [83]}}) 0 0 7 6 t permit).isNone
-- Cancellation needs its own current grant but can survive revoked invocation.
#guard (pending.bind fun (m,t,_) => do
 let m := authorityHead m {m.system.view with authority := {m.system.view.authority with revoked := [10,81]}}
 let permit ← MixedCancellation.authorize m.system m.events.length t 0 0 7 6
 cancel m 0 0 7 6 t permit).isSome
end MirroreaProofFirst.MixedCancelControls
