import MixedReferenceCancellation
import MixedCatalogTransitions
import OwnerMetadataManagement

namespace MirroreaProofFirst.MixedReferenceStore
open ReferenceOwner MixedReferenceHistory

inductive Occurrence where
  | core (event : MixedRequestCore.Occurrence)
  | binding (context : ReferenceOwner.Context)
  | metadata (context : OwnerMetadataManagement.Context)
  | cancellation (permit : MixedReferenceCancellation.Permit)
  deriving DecidableEq

structure Machine (p a : Nat) where
  core : MixedRequestCore.Machine p a
  bindings : List (Option Binding)
  history : List (Frame p a)
  events : List Occurrence

def frame (core : MixedRequestCore.Machine p a) : Frame p a :=
  ⟨core.system,core.system.controlPolicy 13⟩

def Floor (s : MixedInstanceState.State d p n) (row : Option Binding) : Prop :=
  ∀ binding, row = some binding → MixedFallbackStatic.Admissible s binding.request.chain
def floorCheck (s : MixedInstanceState.State d p n) : Option Binding → Bool
  | none => true
  | some binding => match MixedFallbackStatic.check s binding.request.chain with | .ok _ => true | .error _ => false

theorem floor_exact (s : MixedInstanceState.State d p n) (row : Option Binding) : floorCheck s row = true ↔ Floor s row := by
  cases row with
  | none => simp [floorCheck,Floor]
  | some binding =>
      have admitted := MixedFallbackStatic.check_exact s binding.request.chain
      cases h : MixedFallbackStatic.check s binding.request.chain with
      | error reason => simp [h] at admitted; simp [floorCheck,Floor,h,admitted]
      | ok value => cases value; simp [h] at admitted; simp [floorCheck,Floor,h,admitted]

def Floors (s : MixedInstanceState.State d p n) (rows : List (Option Binding)) : Prop :=
  ∀ row ∈ rows, Floor s row
def floorsCheck (s : MixedInstanceState.State d p n) (rows : List (Option Binding)) : Bool := rows.all (floorCheck s)

theorem floors_exact (s : MixedInstanceState.State d p n) (rows : List (Option Binding)) :
    floorsCheck s rows = true ↔ Floors s rows := by simp [floorsCheck,Floors,List.all_eq_true,floor_exact]

def coreEvents (events : List Occurrence) : List MixedRequestCore.Occurrence :=
  events.filterMap fun event => match event with | .core e => some e | .binding _ | .metadata _ => none | .cancellation permit => some (.cancelled permit.core)

def Invariant (m : Machine p a) : Prop :=
  MixedRequestCore.Invariant m.core ∧ MixedCatalogHistory.Invariant m.core.system.configuration ∧
  Floors m.core.system.configuration.state m.bindings ∧
  (∃ past, m.history = past ++ [frame m.core]) ∧ coreEvents m.events = m.core.events

-- Fresh construction only: no entry imports an arbitrary populated core while
-- dropping its bindings/history. Current authority is an explicit environment
-- input, not generated by typing or this constructor. No restore claim here.
def initial (realm : Nat) (view : WorldProjection.AuthorityView a) (policy : Nat → CurrentUse.Policy) : Machine p a :=
  let state : MixedInstanceState.State 0 p 0 :=
    ⟨realm,fun _ => 0,Fin.elim0,Fin.elim0,Fin.elim0,fun _ => true⟩
  let core : MixedRequestCore.Machine p a :=
    ⟨⟨MixedCompositionCore.config state,view,policy,0,[]⟩,[],[]⟩
  ⟨core,[],[frame core],[]⟩

theorem initial_invariant (realm : Nat) (view : WorldProjection.AuthorityView a) (policy : Nat → CurrentUse.Policy) :
    Invariant (initial (p:=p) realm view policy) := by
  have catalog := MixedCatalogHistory.empty_valid
    (⟨realm,fun _ => 0,Fin.elim0,Fin.elim0,Fin.elim0,fun _ => true⟩ : MixedInstanceState.State 0 p 0)
  refine ⟨⟨⟨catalog.toValid,by simp [initial]⟩,by simp [initial],by simp [initial]⟩,catalog,?_,⟨[],rfl⟩,rfl⟩
  simp [initial,Floors]

-- Every actual semantic entry appends the resulting frame. These full finite
-- images are a nonproduction currentness representation, not a persistence API.
def advanceCore (m : Machine p a) (next : MixedRequestCore.Machine p a)
    (event : MixedRequestCore.Occurrence) : Machine p a :=
  {m with core := next,history := m.history ++ [frame next],events := .core event :: m.events}

theorem advanceCore_preserves (m : Machine p a) (next : MixedRequestCore.Machine p a)
    (event : MixedRequestCore.Occurrence) (valid : Invariant m)
    (core : MixedRequestCore.Invariant next) (step : MixedCatalogTransitions.Transition m.core next)
    (floor : Floors next.system.configuration.state m.bindings)
    (actualEvent : next.events = event :: m.core.events) : Invariant (advanceCore m next event) := by
  refine ⟨core,(MixedCatalogTransitions.transition_catalog _ _ valid.2.1 step).1,floor,⟨m.history,rfl⟩,?_⟩
  simpa [advanceCore,coreEvents,← valid.2.2.2.2] using actualEvent.symm

-- The floor test is on the tentative result of ONE real authorized core
-- operation. Rejection commits neither that operation nor a fabricated event.
def manage (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (raw : MixedCompositionCore.Raw) : Option (Machine p a × Option Nat) := do
  let (next,created) ← MixedRequestCore.manage m.core member place principal id raw
  if floorsCheck next.system.configuration.state m.bindings then
    some (advanceCore m next (.management (MixedManagementEntry.current m.core.system member place principal id raw) created),created)
  else none

theorem manage_parts (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (raw : MixedCompositionCore.Raw) (result : Machine p a × Option Nat)
    (accepted : manage m member place principal id raw = some result) :
    ∃ next created, MixedRequestCore.manage m.core member place principal id raw = some (next,created) ∧
      Floors next.system.configuration.state m.bindings ∧
      result = (advanceCore m next (.management (MixedManagementEntry.current m.core.system member place principal id raw) created),created) := by
  unfold manage at accepted
  cases hr : MixedRequestCore.manage m.core member place principal id raw with
  | none => simp [hr] at accepted
  | some pair =>
      obtain ⟨next,created⟩ := pair
      simp only [hr,Option.bind_eq_bind,Option.bind_some] at accepted
      split at accepted
      · rename_i checked
        exact ⟨next,created,rfl,(floors_exact _ _).mp checked,(Option.some.inj accepted).symm⟩
      · cases accepted

theorem manage_preserves (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (raw : MixedCompositionCore.Raw) (result : Machine p a × Option Nat) (valid : Invariant m)
    (accepted : manage m member place principal id raw = some result) :
    Invariant result.1 ∧ result.1.bindings = m.bindings ∧
      ∃ current, result.1.history = m.history ++ [current] := by
  obtain ⟨next,created,coreRun,floor,rfl⟩ := manage_parts _ _ _ _ _ _ _ accepted
  have actualEvent : next.events = .management (MixedManagementEntry.current m.core.system member place principal id raw) created :: m.core.events := by
    obtain ⟨_,e,cfg,created',_,_,eq⟩ := MixedRequestCore.manage_parts coreRun
    cases eq
    rfl
  exact ⟨advanceCore_preserves _ _ _ valid (MixedRequestCore.manage_preserves valid.1 coreRun)
    (.management coreRun) floor actualEvent,rfl,⟨_,rfl⟩⟩

theorem manage_complete (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (raw : MixedCompositionCore.Raw) (next : MixedRequestCore.Machine p a) (created : Option Nat)
    (coreRun : MixedRequestCore.manage m.core member place principal id raw = some (next,created))
    (floor : Floors next.system.configuration.state m.bindings) :
    ∃ result, manage m member place principal id raw = some result := by
  simp [manage,coreRun,(floors_exact _ _).mpr floor]

def authorityHead (m : Machine p a) (view : WorldProjection.AuthorityView a) : Machine p a :=
  advanceCore m (MixedRequestCore.authorityHead m.core view) (.authorityHead view.generation)

theorem authorityHead_preserves (m : Machine p a) (view : WorldProjection.AuthorityView a) (valid : Invariant m) :
    Invariant (authorityHead m view) ∧ (authorityHead m view).bindings = m.bindings ∧
      (authorityHead m view).history = m.history ++ [frame (MixedRequestCore.authorityHead m.core view)] := by
  exact ⟨advanceCore_preserves _ _ _ valid (MixedRequestCore.head_preserves valid.1)
    .authority valid.2.2.1 rfl,rfl,rfl⟩

-- A start adds an actual request occurrence. The duplicated system frame is
-- harmless and keeps history/event correspondence explicit; serial need not move.
def start (m : Machine p a) (member : Fin a) (place : Fin p) (principal id key : Nat) (argument : Int) :
    Option (Machine p a × InvocationBoundary.Ticket) := do
  let (next,ticket) ← MixedRequestCore.startPure m.core member place principal id key argument
  return (advanceCore m next (.requested (.pure ticket)),ticket)

theorem start_preserves (m : Machine p a) (member : Fin a) (place : Fin p) (principal id key : Nat) (argument : Int)
    (result : Machine p a × InvocationBoundary.Ticket) (valid : Invariant m)
    (accepted : start m member place principal id key argument = some result) :
    Invariant result.1 ∧ result.1.bindings = m.bindings ∧ ∃ current, result.1.history = m.history ++ [current] := by
  unfold start at accepted
  cases hr : MixedRequestCore.startPure m.core member place principal id key argument with
  | none => simp [hr] at accepted
  | some pair =>
      obtain ⟨next,ticket⟩ := pair
      simp only [hr,Option.bind_eq_bind,Option.bind_some,Option.pure_def,Option.some.injEq] at accepted
      subst result
      have nextEq := (MixedRequestCore.startPure_parts hr).2.2
      change next = MixedRequestCore.enqueue m.core (.pure ticket) at nextEq
      have floor : Floors next.system.configuration.state m.bindings := by rw [nextEq]; exact valid.2.2.1
      have actualEvent : next.events = .requested (.pure ticket) :: m.core.events := by rw [nextEq]; rfl
      exact ⟨advanceCore_preserves _ _ _ valid (MixedRequestCore.startPure_preserves valid.1 hr)
        (.request hr) floor actualEvent,rfl,⟨_,rfl⟩⟩

-- Lower core-ticket helper. The admitted ReferenceExecution entry checks its
-- total saved classification and continuous reference/holding protection first.
-- This helper alone is not an admitted source or protected-engine transition.
def finishPlain (m : Machine p a) (ticket : InvocationBoundary.Ticket) (value : Int) : Option (Machine p a) := do
  let next ← MixedRequestCore.finishPure m.core ticket value
  return advanceCore m next (.pureResult ticket value)

theorem finishPlain_preserves (m : Machine p a) (ticket : InvocationBoundary.Ticket) (value : Int)
    (result : Machine p a) (valid : Invariant m) (accepted : finishPlain m ticket value = some result) :
    Invariant result ∧ result.bindings = m.bindings ∧ ∃ current, result.history = m.history ++ [current] := by
  unfold finishPlain at accepted
  cases hr : MixedRequestCore.finishPure m.core ticket value with
  | none => simp [hr] at accepted
  | some next =>
      simp only [hr,Option.bind_eq_bind,Option.bind_some,Option.pure_def,Option.some.injEq] at accepted
      subst result
      have nextEq := (MixedRequestCore.finishPure_parts hr).2.2.2
      have floor : Floors next.system.configuration.state m.bindings := by rw [nextEq]; exact valid.2.2.1
      have actualEvent : next.events = .pureResult ticket value :: m.core.events := by rw [nextEq]; rfl
      exact ⟨advanceCore_preserves _ _ _ valid (MixedRequestCore.finishPure_preserves valid.1 hr)
        (.result hr) floor actualEvent,rfl,⟨_,rfl⟩⟩

def cancelled (m : Machine p a) (next : MixedRequestCore.Machine p a)
    (permit : MixedReferenceCancellation.Permit) : Machine p a :=
  {m with core := next,history := m.history ++ [frame next],events := .cancellation permit :: m.events}

def cancel (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (entry : ReferenceExecution.Pending) (permit : MixedReferenceCancellation.Permit) : Option (Machine p a) := do
  if !MixedReferenceCancellation.check m.core.system m.core.events.length m.events.length entry member place principal id permit then none else do
    let next ← MixedCancelEntry.cancel m.core member place principal id entry.ticket permit.core
    return cancelled m next permit

theorem cancel_parts (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (entry : ReferenceExecution.Pending) (permit : MixedReferenceCancellation.Permit) (result : Machine p a)
    (accepted : cancel m member place principal id entry permit = some result) :
    MixedReferenceCancellation.Submitted m.core.system m.core.events.length m.events.length entry member place principal id permit ∧
      ∃ next, MixedCancelEntry.cancel m.core member place principal id entry.ticket permit.core = some next ∧
        result = cancelled m next permit := by
  unfold cancel at accepted
  split at accepted
  · cases accepted
  · rename_i checked
    have yes : MixedReferenceCancellation.check m.core.system m.core.events.length m.events.length entry member place principal id permit = true := by simpa using checked
    cases run : MixedCancelEntry.cancel m.core member place principal id entry.ticket permit.core with
    | none => simp [run] at accepted
    | some next =>
        simp only [run,Option.bind_eq_bind,Option.bind_some,Option.pure_def,Option.some.injEq] at accepted
        exact ⟨(MixedReferenceCancellation.check_exact _ _ _ _ _ _ _ _ _).mp yes,next,rfl,accepted.symm⟩

theorem cancel_preserves (m : Machine p a) (member : Fin a) (place : Fin p) (principal id : Nat)
    (entry : ReferenceExecution.Pending) (permit : MixedReferenceCancellation.Permit) (result : Machine p a)
    (valid : Invariant m) (accepted : cancel m member place principal id entry permit = some result) :
    Invariant result ∧ result.bindings = m.bindings ∧ ∃ current, result.history = m.history ++ [current] := by
  obtain ⟨_,next,run,rfl⟩ := cancel_parts _ _ _ _ _ _ _ _ accepted
  have core := MixedCancelEntry.cancel_preserves _ _ _ _ _ _ _ _ valid.1 run
  obtain ⟨_,_,_,_,rfl⟩ := MixedCancelEntry.cancel_parts _ _ _ _ _ _ _ _ run
  refine ⟨⟨core,valid.2.1,valid.2.2.1,⟨m.history,rfl⟩,?_⟩,rfl,⟨_,rfl⟩⟩
  simpa [cancelled,coreEvents,MixedCancelEntry.abandon] using valid.2.2.2.2

-- Owner request adds its real occurrence/frame while preserving current pure
-- binding floors. Supplied source origin/captures remain outer admission premises.
def startOwner (m : Machine p a) (member : Fin a) (place : Fin p) (principal id key : Nat)
 (origin : OwnerEffectService.Origin) (args : List CurrentUse.Scalar) :
 Option (Machine p a × OwnerSavedPending.Saved) := do
 let (next,saved) ← MixedRequestCore.startOwner m.core member place principal id key origin args
 return (advanceCore m next (.requested (.owner saved)),saved)

theorem startOwner_preserves (m : Machine p a) (member : Fin a) (place : Fin p) (principal id key : Nat)
 (origin : OwnerEffectService.Origin) (args : List CurrentUse.Scalar)
 (result : Machine p a × OwnerSavedPending.Saved) (valid : Invariant m)
 (accepted : startOwner m member place principal id key origin args = some result) :
 Invariant result.1 ∧ result.1.bindings = m.bindings ∧ ∃ current, result.1.history = m.history ++ [current] := by
 unfold startOwner at accepted
 cases run : MixedRequestCore.startOwner m.core member place principal id key origin args with
 | none => simp [run] at accepted
 | some pair =>
   obtain ⟨next,saved⟩ := pair
   simp only [run,Option.bind_eq_bind,Option.bind_some,Option.pure_def,Option.some.injEq] at accepted
   subst result
   have eq := (MixedRequestCore.startOwner_parts run).2
   dsimp only at eq
   have floor : Floors next.system.configuration.state m.bindings := by rw [eq]; exact valid.2.2.1
   have event : next.events = .requested (.owner saved) :: m.core.events := by rw [eq]; rfl
   exact ⟨advanceCore_preserves _ _ _ valid (MixedRequestCore.startOwner_preserves valid.1 run)
     (.ownerRequest run) floor event,rfl,⟨_,rfl⟩⟩

def finishOwner (m : Machine p a) (saved received : OwnerSavedPending.Saved) (evidence : CurrentUse.Evidence) : Option (Machine p a) := do
 let next ← MixedRequestCore.finishOwner m.core saved received evidence
 return advanceCore m next (.ownerAcknowledged saved evidence)

theorem finishOwner_parts (m : Machine p a)
 (accepted : finishOwner m saved received evidence = some next) :
 ∃ core, MixedRequestCore.finishOwner m.core saved received evidence = some core ∧
 next = advanceCore m core (.ownerAcknowledged saved evidence) := by
 unfold finishOwner at accepted
 cases run : MixedRequestCore.finishOwner m.core saved received evidence with
 | none => simp [run] at accepted
 | some core =>
   simp only [run,Option.bind_eq_bind,Option.bind_some,Option.pure_def,Option.some.injEq] at accepted
   exact ⟨core,rfl,accepted.symm⟩

theorem finishOwner_preserves (m : Machine p a) (valid : Invariant m)
 (accepted : finishOwner m saved received evidence = some next) :
 Invariant next ∧ next.bindings = m.bindings ∧ ∃ current, next.history = m.history ++ [current] := by
 obtain ⟨core,run,rfl⟩ := finishOwner_parts m accepted
 have eq := (MixedRequestCore.finishOwner_parts run).2.2
 obtain ⟨_,_,_,_,_,same⟩ := eq
 have floor : Floors core.system.configuration.state m.bindings := by rw [same]; exact valid.2.2.1
 have event : core.events = .ownerAcknowledged saved evidence :: m.core.events := by rw [same]; rfl
 exact ⟨advanceCore_preserves _ _ _ valid (MixedRequestCore.finishOwner_preserves valid.1 run)
   (.ownerAcknowledged run) floor event,rfl,⟨_,rfl⟩⟩

#print axioms finishOwner_parts
#print axioms finishOwner_preserves
#print axioms startOwner_preserves
#print axioms cancel_preserves
#print axioms floor_exact
#print axioms floors_exact
#print axioms advanceCore_preserves
#print axioms manage_preserves
#print axioms manage_complete
#print axioms authorityHead_preserves
#print axioms start_preserves
#print axioms finishPlain_preserves
#print axioms initial_invariant
end MirroreaProofFirst.MixedReferenceStore
