import MixedManagementEntry
import MixedCatalogControls
namespace MirroreaProofFirst.MixedManagementControls
open MixedCompositionCore MixedManagementEntry WorldProjection CurrentUse

-- All authority below is an explicit LAB fixture, not generated by definition
-- checking. Existing pure-only controls do not acquire owner-specific powers.
def ownerControl : Claim :=
 {ManagementEntry.Controls.claim with id := 82,actions := [17,18,19,20,21],targets := List.range 16}
def view : AuthorityView 1 :=
 {MixedCatalogControls.view with authority :=
   {MixedCatalogControls.view.authority with issued :=
      MixedCatalogControls.view.authority.issued ++ [ManagementEntry.Controls.claim,ownerControl]}}
def initial : System 3 1 :=
 ⟨config (⟨91,fun _ => 0,Fin.elim0,Fin.elim0,Fin.elim0,fun _ => true⟩ : MixedInstanceState.State 0 3 0),
  view,(fun _ => ManagementEntry.Controls.policy),0,[]⟩
def pureCode : Raw := .register (.pure InstancePrograms.Controls.original) none
def ownerCode : Raw := .register (.owner MixedCatalogControls.add) none
def pureRegistered := perform initial 0 0 7 0 pureCode
def pureBuilt := pureRegistered.bind fun (s,_) => perform s 0 0 7 1 (.instantiate 0 7 [0] none .top)
def ownerRegistered := pureBuilt.bind fun (s,_) => perform s 0 0 7 2 ownerCode
def bothBuilt := ownerRegistered.bind fun (s,_) => perform s 0 0 7 3 (.instantiate 1 7 [0] none .top)
#guard (bothBuilt.map fun (s,_) => s.configuration.definitions) = some 2
#guard (bothBuilt.map fun (s,_) => s.configuration.count) = some 2
#guard (bothBuilt.map fun (s,_) => s.serial) = some 4
#guard (bothBuilt.map fun (s,_) => s.used.map UseId.request) = some [3,2,1,0]
#guard (perform {initial with view := {view with authority := {view.authority with revoked := [82]}}}
  0 0 7 0 ownerCode).isNone
#guard (perform {initial with view := {view with authority := {view.authority with revoked := [82]}}}
  0 0 7 0 pureCode).isSome
#guard (authorize initial 0 0 7 0 ownerCode).isSome
#guard ((authorize initial 0 0 7 0 pureCode).bind fun e => commit initial 0 0 7 0 ownerCode e).isNone
#guard ((authorize initial 0 0 7 0 ownerCode).bind fun e => commit initial 0 0 7 0
 (.register (.owner {MixedCatalogControls.add with body := ⟨0,.integer 99⟩}) none) e).isNone
#guard (ownerRegistered.bind fun (s,_) => perform
  {s with view := {s.view with authority := {s.view.authority with revoked := [82]}}}
  0 0 7 3 (.instantiate 1 7 [0] none .top)).isNone
#guard (bothBuilt.bind fun (s,_) => perform s 0 0 7 3 (.retire 0)).isNone

def observed : Option (Int × Option Int × List Int × Bool) := do
 let (s,_) ← bothBuilt
 let data := s.configuration.state
 let pureKey ← index s.configuration.count 0
 let ownerKey ← index s.configuration.count 1
 let .pure pureDefinition := MixedCatalogService.operationDefinition data pureKey | none
 let value ← InstancePrograms.Machine.run pureDefinition.code 2
 let .owner ownerDefinition := MixedCatalogService.operationDefinition data ownerKey | none
 let handle (slot : Slot 1 3 s.configuration.count) : Handle (size 1 3 s.configuration.count) :=
  ⟨data.realm,encode slot,(MixedCatalogService.slotRecord data s.view slot).identity⟩
 let request : UseRequest (size 1 3 s.configuration.count) :=
  ⟨7,handle (.member 0),handle (.locus 0),handle (.moduleSlot ownerKey),handle (.operation ownerKey 0),4,[.integer value]⟩
 let world := MixedCatalogService.world data s.view
 let evidence ← CurrentUse.authorize world.authority (world.policies request.operation.key) (currentContext world request)
 let pending : OwnerEffectService.Pending (size 1 3 s.configuration.count) :=
  ⟨⟨"mixed-management-core",40,12,1,0⟩,request,evidence,ownerDefinition.body⟩
 let initialOwner : OwnerEffectService.Owner (size 1 3 s.configuration.count) := ⟨fun k => if k=0 then some 10 else none,[]⟩
 let result := MixedCatalogService.serve (FallibleFlow.signed 63) data s.view initialOwner pending
 return (value,result.1.store 0,result.1.history.map OwnerEffectService.Write.value,
   decide (⟨data.realm,7,4⟩ ∉ s.used))
#guard observed = some (5,some 15,[15],true)
-- Actual admitted management -> same catalog -> actual checked owner evaluator.
-- NOT parsed mixed source, unit continuation, shared queue, or physical network.
end MirroreaProofFirst.MixedManagementControls
