import MirroreaProofFirstOwnerSourceContext
import MirroreaProofFirstCurrentUse
namespace MirroreaProofFirst.OwnerMetadataRegistry
open OwnerStructuredKeys OwnerSourceContext

-- Nonproduction current-owner producer candidate. The checked schema/owner
-- attachment is an explicit input boundary; no theorem certifies the Rust
-- parser or authenticates a raw schema by renaming it. Claims are already-issued
-- records in CurrentUse.World, never generated by this registry.
structure Slot where
 generation : Nat
 labelFloor : Nat
 current : Option Metadata
 deriving DecidableEq, Repr

structure Registry where
 instanceId : Nat
 ownerKey : Nat
 ownerIdentity : CurrentUse.RecordIdentity
 moduleKey : Nat
 moduleIdentity : CurrentUse.RecordIdentity
 code : Nat
 contract : Nat
 ownerName : String
 schema : Schema
 serial : Nat
 slots : List (Key × Slot)
 used : List CurrentUse.UseId

-- Tombstones stay in slots. A field's generation and label floor survive
-- retirement and re-creation; unrelated keys do not invalidate each other.
def slot (s : Registry) (key : Key) : Slot :=
 (s.slots.lookup key).getD ⟨0,0,none⟩
def current (s : Registry) (key : Key) : Option Metadata := (slot s key).current

def setSlot (s : Registry) (key : Key) (value : Slot) : Registry :=
 {s with slots := (key,value)::s.slots.filter (fun row => row.1 != key), serial := s.serial+1}

theorem set_same : slot (setSlot s key value) key = value := by
 simp [slot,setSlot]

theorem set_other (different : other ≠ key) : slot (setSlot s key value) other = slot s other := by
 simp only [slot,setSlot,List.lookup_cons,beq_eq_false_iff_ne.mpr different,cond_false]
 congr 1
 induction s.slots with
 | nil => rfl
 | cons row rest ih =>
   obtain ⟨name,metadata⟩ := row
   by_cases removed : name=key
   · subst name
     simp [List.lookup_cons,beq_eq_false_iff_ne.mpr different,ih]
   · by_cases found : other=name
     · subst other; simp [removed]
     · simp [removed,List.lookup_cons,beq_eq_false_iff_ne.mpr found,ih]

inductive Change where
 | activate (key : Key) (label : Nat)
 | retire (key : Key)
 deriving DecidableEq, Repr

def Change.key : Change → Key | .activate k _ | .retire k => k
-- Distinct internal research actions. Existing invoke/register claims do not
-- automatically cover them. No issuer, grant or production action tag added.
def Change.action : Change → Nat | .activate .. => 22 | .retire .. => 23

def prepare (s : Registry) : Change → Option Slot
 | .activate key label => do
   let declaration ← select s.schema key
   if declaration.owner = s.ownerName ∧ declaration.typeName = "Int" ∧
     (slot s key).labelFloor ≤ label then
     some ⟨(slot s key).generation+1,label,some ⟨declaration,(slot s key).generation+1,label⟩⟩
   else none
 | .retire key => do
   let _ ← current s key
   some ⟨(slot s key).generation+1,(slot s key).labelFloor,none⟩

-- Independent structural/lifetime rule. Generation is reconstructed, not a
-- submitted value; visibility is not used for classification or authority.
inductive Prepares (s : Registry) : Change → Slot → Prop where
 | activate : Declared s.schema key declaration → declaration.owner = s.ownerName →
   declaration.typeName = "Int" → (slot s key).labelFloor ≤ label →
   Prepares s (.activate key label)
     ⟨(slot s key).generation+1,label,some ⟨declaration,(slot s key).generation+1,label⟩⟩
 | retire : current s key = some metadata → Prepares s (.retire key)
     ⟨(slot s key).generation+1,(slot s key).labelFloor,none⟩

theorem prepare_exact : prepare s change = some next ↔ Prepares s change next := by
 cases change with
 | activate key label =>
   constructor
   · intro accepted
     cases found : select s.schema key with
     | none => simp [prepare,found] at accepted
     | some declaration =>
       simp only [prepare,found,Option.bind_eq_bind,Option.bind_some] at accepted
       split at accepted
       · rename_i good
         cases accepted
         exact .activate (select_exact.mp found) good.1 good.2.1 good.2.2
       · cases accepted
   · intro rule
     cases rule with
     | activate declared owned integer floor => simp [prepare,select_exact.mpr declared,owned,integer,floor]
 | retire key =>
   constructor
   · intro accepted
     cases found : current s key with
     | none => simp [prepare,found] at accepted
     | some metadata =>
       simp only [prepare,found,Option.bind_eq_bind,Option.bind_some,Option.some.injEq] at accepted
       subst next
       exact .retire found
   · intro rule
     cases rule with
     | retire found => simp [prepare,found]

theorem prepared_strict_generation (rule : Prepares s change next) :
 next.generation = (slot s change.key).generation+1 := by cases rule <;> rfl

theorem prepared_label_floor (rule : Prepares s change next) :
 (slot s change.key).labelFloor ≤ next.labelFloor := by
 cases rule with
 | activate _ _ _ floor => exact floor
 | retire _ => exact Nat.le_refl _

-- Full structural admission context. The extra payload is bound to the same
-- current-use evidence, actor/locus/module/code/contract/generation. Model
-- equality is not a signature; physical sealed custody remains a separate gate.
structure Context where
 use : CurrentUse.Context
 ownerIdentity : CurrentUse.RecordIdentity
 ownerName : String
 schema : Schema
 serial : Nat
 change : Change
 deriving DecidableEq, Repr
structure Evidence where
 context : Context
 authority : CurrentUse.Evidence
 deriving DecidableEq, Repr

def context (s : Registry) (world : CurrentUse.World n) (request : CurrentUse.UseRequest n)
 (change : Change) : Context :=
 ⟨CurrentUse.currentContext world request,s.ownerIdentity,s.ownerName,s.schema,s.serial,change⟩

def Attached (s : Registry) (world : CurrentUse.World n) (request : CurrentUse.UseRequest n)
 (change : Change) : Prop :=
 s.instanceId = world.instanceId ∧ request.locus.key.val = s.ownerKey ∧
 request.locus.identity = s.ownerIdentity ∧ request.moduleHandle.key.val = s.moduleKey ∧
 request.moduleHandle.identity = s.moduleIdentity ∧
 (world.records request.operation.key).code = s.code ∧
 (world.records request.operation.key).contract = s.contract ∧
 (world.records request.operation.key).action = change.action

instance : Decidable (Attached s world request change) := by unfold Attached; infer_instance

def check (s : Registry) (world : CurrentUse.World n) (request : CurrentUse.UseRequest n)
 (change : Change) (evidence : Evidence) : Bool :=
 decide (evidence.context = context s world request change) &&
 decide (Attached s world request change) && CurrentUse.checkUse world request evidence.authority


def Allowed (s : Registry) (world : CurrentUse.World n) (request : CurrentUse.UseRequest n)
 (change : Change) : Prop := Attached s world request change ∧ CurrentUse.CurrentUse world request

theorem check_sound (accepted : check s world request change evidence = true) :
 Allowed s world request change ∧ evidence.context = context s world request change := by
 have parts : (evidence.context = context s world request change ∧ Attached s world request change) ∧
   CurrentUse.checkUse world request evidence.authority = true := by simpa [check] using accepted
 exact ⟨⟨parts.1.2,CurrentUse.checkUse_sound _ _ _ parts.2⟩,parts.1.1⟩

theorem check_complete (allowed : Allowed s world request change) :
 ∃ evidence, check s world request change evidence = true := by
 obtain ⟨authority,checked⟩ := CurrentUse.checkUse_complete world request allowed.2
 exact ⟨⟨context s world request change,authority⟩,by simp [check,allowed.1,checked]⟩

def useId (world : CurrentUse.World n) (request : CurrentUse.UseRequest n) : CurrentUse.UseId :=
 (CurrentUse.currentContext world request).useId

def after (s : Registry) (world : CurrentUse.World n) (request : CurrentUse.UseRequest n)
 (change : Change) (next : Slot) : Registry :=
 {setSlot s change.key next with used := useId world request::s.used}

def commit (s : Registry) (world : CurrentUse.World n) (request : CurrentUse.UseRequest n)
 (change : Change) (evidence : Evidence) : Option Registry := do
 if s.used.contains (useId world request) || !check s world request change evidence then none else do
 let next ← prepare s change
 return after s world request change next

theorem commit_parts (accepted : commit s world request change evidence = some result) :
 useId world request ∉ s.used ∧ Allowed s world request change ∧
 evidence.context = context s world request change ∧
 ∃ next, Prepares s change next ∧ result = after s world request change next := by
 unfold commit at accepted
 split at accepted
 · cases accepted
 · rename_i openGate
   have gates : useId world request ∉ s.used ∧ check s world request change evidence = true := by
     simpa using openGate
   cases prepared : prepare s change with
   | none => simp [prepared] at accepted
   | some next =>
     simp only [prepared,Option.bind_eq_bind,Option.bind_some,Option.pure_def,Option.some.injEq] at accepted
     exact ⟨gates.1,(check_sound gates.2).1,(check_sound gates.2).2,next,prepare_exact.mp prepared,accepted.symm⟩

theorem commit_relative_complete (fresh : useId world request ∉ s.used)
 (allowed : Allowed s world request change) (rule : Prepares s change next) :
 ∃ evidence, commit s world request change evidence = some (after s world request change next) := by
 obtain ⟨evidence,checked⟩ := check_complete allowed
 exact ⟨evidence,by simp [commit,fresh,checked,prepare_exact.mpr rule]⟩

theorem commit_no_repeat (accepted : commit s world request change evidence = some result) :
 commit result world request other otherEvidence = none := by
 obtain ⟨_,_,_,next,_,rfl⟩ := commit_parts accepted
 simp [commit,after]

theorem commit_other_key (accepted : commit s world request change evidence = some result)
 (different : key ≠ change.key) : current result key = current s key := by
 obtain ⟨_,_,_,next,_,rfl⟩ := commit_parts accepted
 exact congrArg Slot.current (set_other (s:=s) (value:=next) different)

theorem commit_generation (accepted : commit s world request change evidence = some result) :
 (slot result change.key).generation = (slot s change.key).generation+1 := by
 obtain ⟨_,_,_,next,prepared,rfl⟩ := commit_parts accepted
 change (slot (setSlot s change.key next) change.key).generation = _
 rw [set_same]
 exact prepared_strict_generation prepared

theorem commit_floor (accepted : commit s world request change evidence = some result) :
 (slot s change.key).labelFloor ≤ (slot result change.key).labelFloor := by
 obtain ⟨_,_,_,next,prepared,rfl⟩ := commit_parts accepted
 change _ ≤ (slot (setSlot s change.key next) change.key).labelFloor
 rw [set_same]
 exact prepared_label_floor prepared

-- Live metadata really comes from a unique checked declaration and one producer
-- transition. This invariant is over constructed states, not a premise equal
-- to the desired origin conclusion.
def Consistent (s : Registry) : Prop :=
 ∀ key metadata, current s key = some metadata →
 Declared s.schema key metadata.declaration ∧ metadata.declaration.owner = s.ownerName ∧
 metadata.declaration.typeName = "Int" ∧ metadata.generation = (slot s key).generation ∧
 metadata.label = (slot s key).labelFloor

theorem prepared_consistent (rule : Prepares s change next) (found : next.current = some metadata) :
 Declared s.schema change.key metadata.declaration ∧ metadata.declaration.owner = s.ownerName ∧
 metadata.declaration.typeName = "Int" ∧ metadata.generation = next.generation ∧ metadata.label = next.labelFloor := by
 cases rule with
 | activate declared owner integer _ => cases found; exact ⟨declared,owner,integer,rfl,rfl⟩
 | retire _ => cases found

theorem commit_consistent (valid : Consistent s)
 (accepted : commit s world request change evidence = some result) : Consistent result := by
 obtain ⟨_,_,_,next,prepared,rfl⟩ := commit_parts accepted
 intro key metadata found
 by_cases same : key=change.key
 · subst key
   have currentNext : next.current = some metadata := by
     change (slot (setSlot s change.key next) change.key).current = some metadata at found
     simpa only [set_same] using found
   have correct := prepared_consistent prepared currentNext
   simpa only [after,setSlot,slot,List.lookup_cons,beq_self_eq_true,cond_true,Option.getD_some] using correct
 · have retained := set_other (s:=s) (value:=next) same
   have oldFound : current s key = some metadata := by
     change (slot (setSlot s change.key next) key).current = _ at found
     rw [retained] at found
     exact found
   have correct := valid key metadata oldFound
   change Declared s.schema key metadata.declaration ∧ metadata.declaration.owner = s.ownerName ∧
     metadata.declaration.typeName = "Int" ∧ metadata.generation = (slot (setSlot s change.key next) key).generation ∧
     metadata.label = (slot (setSlot s change.key next) key).labelFloor
   rw [retained]
   exact correct

theorem empty_consistent (empty : s.slots = []) : Consistent s := by
 intro key metadata found
 simp [current,slot,empty] at found

inductive Rooted (root : Registry) : Registry → Prop where
 | initial : root.slots = [] → root.used = [] → Rooted root root
 | commit {n : Nat} {world : CurrentUse.World n} {request : CurrentUse.UseRequest n} :
   Rooted root s → commit s world request change evidence = some result → Rooted root result

theorem rooted_consistent (path : Rooted root s) : Consistent s := by
 induction path with
 | initial empty _ => exact empty_consistent empty
 | commit _ accepted ih => exact commit_consistent ih accepted

theorem rooted_unique (path : Rooted root s) : s.used.Nodup := by
 induction path with
 | initial _ empty => simp [empty]
 | commit _ accepted ih =>
   obtain ⟨fresh,_,_,next,_,rfl⟩ := commit_parts accepted
   exact List.nodup_cons.mpr ⟨fresh,ih⟩

def IssuedAt (root : Registry) (key : Key) (metadata : Metadata) : Prop :=
 ∃ (n : Nat) (before result : Registry) (world : CurrentUse.World n)
   (request : CurrentUse.UseRequest n) (evidence : Evidence) (label : Nat),
   Rooted root before ∧
   commit before world request (.activate key label) evidence = some result ∧
   current result key = some metadata

-- A surviving record has an actual successful producer in the admitted history.
-- Its historical authorization is NOT a present-use grant or an authenticated
-- physical history/head. Those require the enclosing session and current gate.
theorem rooted_origin (path : Rooted root s) (present : current s key = some metadata) :
 IssuedAt root key metadata := by
 induction path with
 | initial empty _ => simp [current,slot,empty] at present
 | @commit before change evidence result n world request path accepted ih =>
   by_cases same : key=change.key
   · obtain ⟨_,_,_,next,prepared,equal⟩ := commit_parts accepted
     cases prepared with
     | @activate target declaration label _ _ _ _ =>
       subst key
       exact ⟨n,before,result,world,request,evidence,label,path,accepted,present⟩
     | @retire target old found =>
       subst key
       rw [equal] at present
       change (slot (setSlot before target _) target).current = some metadata at present
       rw [set_same] at present
       cases present
   · exact ih ((commit_other_key accepted same) ▸ present)

theorem changed_binding_refused (valid : Consistent s)
 (before : current s binding.key = some binding.metadata)
 (changedKey : change.key = binding.key)
 (accepted : commit s world request change evidence = some result) :
 OwnerSourceContext.usable result.schema (current result) binding = false := by
 cases checked : OwnerSourceContext.usable result.schema (current result) binding with
 | false => rfl
 | true =>
   have after := (OwnerSourceContext.usable_exact.mp checked).2
   have oldGen := (valid binding.key binding.metadata before).2.2.2.1
   have newGen := (commit_consistent valid accepted binding.key binding.metadata after).2.2.2.1
   have bump := commit_generation accepted
   rw [changedKey] at bump
   omega

theorem no_authority_refused (empty : world.authority.issued = []) :
 commit s world request change evidence = none := by
 cases result : commit s world request change evidence with
 | none => rfl
 | some next =>
   obtain ⟨_,allowed,_,_⟩ := commit_parts result
   obtain ⟨_,_,_,_,_,_,_,auth⟩ := allowed.2
   exact False.elim ((CurrentUse.no_claim_no_authorization _ _ _ _ empty) auth)

theorem changed_payload_refused (different : evidence.context.change ≠ change) :
 check s world request change evidence = false := by
 have differentContext : evidence.context ≠ context s world request change := by
   intro same
   exact different (congrArg Context.change same)
 simp [check,differentContext]

#print axioms rooted_consistent
#print axioms rooted_unique
#print axioms rooted_origin
#print axioms changed_binding_refused
#print axioms no_authority_refused
#print axioms changed_payload_refused
#print axioms prepare_exact
#print axioms set_other
#print axioms check_sound
#print axioms check_complete
#print axioms commit_parts
#print axioms commit_relative_complete
#print axioms commit_no_repeat
#print axioms commit_generation
#print axioms commit_floor
#print axioms commit_consistent
end MirroreaProofFirst.OwnerMetadataRegistry
